### ISSUE TITLE
Use DefaultAWSCredentialsProviderChain instead of only relying on static AWS credentials from config file

### ISSUE THREAD

**Issue by abhide** [vinyldns/vinyldns#1008]
**Is your feature request related to a problem? Please describe.**
Currently, VinylDNS uses AWS credential statically specified from application.conf to create SQS client.
This limits how credentials are supplied to the application. 

In cases where AWS credentials are dynamically generated by some other agent and made available to the application at runtime this approach doesn't work well. 
For eg:
VinylDNS is deployed on Kubernetes cluster and AWS credentials are generated using [KIAM](https://github.com/uswitch/kiam). In this case the EC2 Metadata Service provider is used to retrieve AWS creds and connect with the corresponding AWS endpoint

**Describe the solution you'd like**
We could use https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html that looks credentials in certain order and selects the most relevant method.

**Comment by pauljamescleary** [comment]
Makes sense, right now we support environment variables or java system properties, but not the EC2 Metadata Service.

I imagine the same would apply to the Route53 backend provider.

We could attempt to load via default provider chain first, and fallback to what might be found in the config file or vice versa.

**Comment by pauljamescleary** [comment]
I see you already have a PR up, great, just commented there

**Comment by pauljamescleary** [comment]
Also, fwiw, there is a `MySqlMessageQueueProvider` that uses the database as a message queue that is fine for smaller workloads.

I do like SQS because it is virtually free and you get some monitoring to boot.  Just have to watch deadletters where messages wind up if they retry N times
