### ISSUE TITLE
Allow optional parameters in configuration in vinyldns-api/vinyldns-portal

### ISSUE THREAD

**Issue by abhide** [vinyldns/vinyldns#1020]
**Describe the bug**
reference.conf covers all the parameters that are required for vinyldns-api and vinyldns-portal. 
application.conf can override some values for parameters specified in reference.conf. 
However, looks like there is way to support optional configuration parameters. 
For example, 
https://github.com/vinyldns/vinyldns/pull/1014 makes `secret-key` and `access-key` optional for SQS. 
If these parameters aren't specified in `application.conf` then `AWSDefaultCredentialsChain` should be used for authentication. 
However, if these parameters are omitted in `application.conf` then `access-key=x` and `secret-key=x` get picked up from `reference.conf` and things don't work as expected. 

**VinylDNS Version**
Master branch

**Comment by pauljamescleary** [comment]
Lightbend config "how to handle defaults" recommends adding a value to `reference.conf` for default values.  https://github.com/lightbend/config#how-to-handle-defaults

By in large, that is what we do, as well as the ecosystem in general.  There are special cases, and we can do an `Option` or a `Config.hasPath`, etc. which is ok.

In the cases where application logic should handle the scenario where a configuration is absent, it is best to make it an `Option` or use `Config.hasPath` and leave it out of `reference.conf`.

I recommend we close this issue, and remove from `reference.conf` when there is an application level decision on how to handle the absence of a config value.

**Comment by abhide** [comment]
Makes sense. we can close this issue. we have deleted `secret-key` and `access-key` values for AWS resources from reference.conf in the PR mentioned in this GH issue.
