### ISSUE TITLE
Exception to dotted hostname rule for ACME DNS-01 Challenge

### ISSUE THREAD

**Issue by jhg03a** [vinyldns/vinyldns#1034]
**Is your feature request related to a problem? Please describe.**
In order to make use of ACME based SSL certificate clients, ownership of DNS records are handled through challenges involving HTTP, TLS, DNS before certificates are issued.  If for firewall reasons there is not a path via HTTP or TLS, that only leaves you with the [DNS-01 challenge mechanism](https://tools.ietf.org/html/rfc8555#section-8.4).  In short, the DNS verification method entails generating a temporary DNS TXT record `_acme-challenge.<hostname>.<domainname>` with a verification token string value.  The problem with the existing implementation of VinylDNS today is that in order to create that `_acme-challenge` record, a full zone must be created and enrolled to vinylDNS per host.  While technically possible, it's not practical.  Solving this problem will allow any VinylDNS environment to leverage the ACME protocol for automating SSL certificate creation/renewal from any ACME providing certificate authority such as Let's Encrypt.

**Describe the solution you'd like**
I'd like to see an exception to the existing rule forbidding dotted hostnames for specifically that prefix on TXT records only.  This would alleviate the overhead and zone maintenance costs associated with these temporary records.  If it's something that administrators would like some kind of control over or is only available on certain DNS backends, that's ok.

**Describe alternatives you've considered**
The amount of overhead required to add and delete full SOA zones in addition to onboard/offboarding to vinylDNS is an option, but very significant.  Leveraging either the TLS or HTTP ACME challenge methods is an option if it is internet facing and the webserver software supports serving static directory content or ACME directly.  Both of these conditions are not universally available without creating significant single points of failure and complicated proxy setups to maintain.

**Comment by jhg03a** [comment]
At one time it looks like this might have worked.

https://github.com/vinyldns/vinyldns/pull/587

**Comment by pauljamescleary** [comment]
Others have requested dotted host exemptions.  Would certain zones configured (in the config file) as exempt work?  Maybe regular expression zone name matches?

**Comment by jhg03a** [comment]
As a consumer, the permissions structures are outside my view.  This is a specific use case for a very narrow exception.  All recordset names under this exception should match the regex `_acme-challenge\.[^.]+$`.  If it's something an administrator has to turn on per zone, that's ok.  Less required interaction & micromanagement is more efficient though at the tradeoff of security.

**Comment by pauljamescleary** [comment]
Thanks @jhg03a, I think it is reasonable to be able to do this at a regex / config level
