### ISSUE TITLE
Make VinylDNS version more easily available

### ISSUE THREAD

**Issue by jhg03a** [vinyldns/vinyldns#1039]
**Is your feature request related to a problem? Please describe.**
When attempting to file a bug report, it asks for the VinylDNS version.  As a user with only the UI, I couldn't locate this information.

**Describe the solution you'd like**
I'd like an about/info dialog box option in the dropdown menu with my API key operations.

**Describe alternatives you've considered**
A simple version number in the bottom left of the screen would also work, but a separate dialog lets vinyl supply any other information that might be useful when reporting a bug.

**Comment by remerle** [comment]
You can find the version at the bottom right corner of the portal

![image](https://user-images.githubusercontent.com/1167333/114188407-1e80ff00-9917-11eb-8627-4c7fda302e9a.png)

**Comment by jhg03a** [comment]
Ah, you're right.  I didn't see if because I didn't notice the scroll bar.  I don't know why there's so much blank space.
