### ISSUE TITLE
Use curl instead of wget in shell scripts

### ISSUE THREAD

**Issue by djbooboo** [vinyldns/vinyldns#106]
**Motivation**
WGET is mainly used for file download while the shell scripts in this project need it for verification.  ( HTTP 200 response ).  Curl is a better tool for that plus is used on more platforms.

**Scope of change**

Replace:
* WGET should only be replaced in 3 Shell Scripts found here ( https://github.com/vinyldns/vinyldns/search?l=Shell&q=wget )

Remain:
* WGET should remain here ( https://github.com/vinyldns/vinyldns/search?l=Markdown&q=wget ) for documentation
* WGET should remain here ( https://github.com/vinyldns/vinyldns/blob/master/.travis.yml ) to download protobuf

**Comment by nimaeskandary** [comment]
@djbooboo We can use curl to download protobuf too, in case should we just get rid of it everywhere including docs
