### ISSUE TITLE
ACLs do not honor most permissive access level

### ISSUE THREAD

**Issue by remerle** [vinyldns/vinyldns#1083]
## Background
Given an ACL on zone as follows:

| | |
|--|--|
|Zone|`vinyldns.io`|
|User|`leela`|
|Access Level|`read`|
|Record Mask | n/a |

If user `leela` attempts to create a record `foo` in `vinyldns.io` they will be met with a `400` error and the message
```
"User leela does not have access to create foo.vinyldns.io."
```
This is by design.

## Issue
Assume, now, that we have more than one ACL entry for user `leela`:

| | |
|--|--|
|Zone|`vinyldns.io`|
|User|`leela`|
|Access Level|`read`|
|Record Mask | n/a |

| | |
|--|--|
|Zone|`vinyldns.io`|
|User|`leela`|
|Access Level|`delete`|
|Record Mask | n/a |

Because we have a `delete` entry, user `leela` should be able to create, modify **or** delete records in the `vinyldns.io` zone. However, due to the presence of the `read` ACL entry, the user will receive the same message:
```
"User leela does not have access to create foo.vinyldns.io."
```

This is due to the code here:
https://github.com/vinyldns/vinyldns/blob/e4264fb34cc965fb7bcddaf0148472c4bf890ab0/modules/api/src/main/scala/vinyldns/api/domain/access/AccessValidations.scala#L199-L207

Specifically, the access levels are sorted and the `minimum` _(line 205)_ level is returned. Instead, the expectation is that the **most permissive** level will be returned.

The VinylDNS UI does not make it clear that each subsequent access level includes the previous level, so it's not uncommon for users to include entries for `Read`, `Write`, **and** `Delete` when only `Delete` is needed.

We need to reverse the order and take the most permissive access level and update the documentation to indicate the same. We also need to account for the `No Access` level, so please see the note about `No Access` below as part of this change.

### Important Note about `No Access`
The [public documentation](https://www.vinyldns.io/permissions.html#:~:text=accessLevel%20%2D%20what%20kinds,as%20an%20override.) does not state how permission precedence works, so there should be no expectation of behavior. 

For the different access levels, we can quantify the permissions by their type - are they allowing access, or denying access:

| Access Level | Type |
| -- | -- |
| `Read` | Allow |
| `Write` | Allow |
| `Delete` | Allow |
| `No Access` | Deny |

From a precedence point of view, it's generally the expectation that `deny` rules take precedence of `allow` rules. So, irrespective of what `allow` rules are in place, if there is a matching `deny` rule, it should take precedence.

**Comment by Chalmiller** [comment]
I'd like to assign myself to address this issue. I will follow up with a PR in the coming days.
