### ISSUE TITLE
Create a gravatar for Docker Hub avatar

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#110]
**Motivation**
If you open up kitematic all the other big images have an avatar. We have a nice logo, we should add it to Docker Hub too! 

**Scope of change**
We need a wordpress account to make a gravatar. After the gravatar is made, open up https://hub.docker.com/u/vinyldns/dashboard/, go to settings, and add our gravatar there

**Comment by pauljamescleary** [comment]
Done!
