### ISSUE TITLE
Make release process configurable 

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#112]
**Motivation**
Before making a release public we release internally at Comcast, and run the new version of VinylDNS for some time to ensure there aren't any problems. 

**Scope of change**
We need to be able to configure the release process to either push to the Comcast internal Docker and Maven registries, or to Docker Hub and Maven Central.

Alternatively we could keep the Docker Hub and Maven Central as is, and have another release option that supports publishing everything artifactory

**Comment by pauljamescleary** [comment]
In sbt, you can use `sys.env` pretty much liberally to pull from environment variables.

@nimaeskandary can you list the credentials / keys that would be needed.  We would need minimally:

1. Credentials (realm, endpoint, user, password) for publishing to docker
1. Credentials (realm, endpoint, user, password) for publishing to sonatype
1. ? Key and passphrase for publishing signed images to public docker
1. ? Key and passphrase for publishing signed images to sonatype

@nimaeskandary not sure about the last two items there.  Also, for internal purposes, not sure if we sign aything, so those last two would have to be "optional"

**Comment by pauljamescleary** [comment]
+1 for me on this, I think it is pretty straight forward to use environment variables.  We may want to have some scala code under the `project` directory with some functions so the main `build.sbt` doesn't get unweildy.

**Comment by remerle** [comment]
Closing out this issue as it's > 2 years old.
