### ISSUE TITLE
Hide PTR zones from zone list by default

### ISSUE THREAD

**Issue by jhg03a** [vinyldns/vinyldns#1122]
As a user of the Vinyldns UI with large numbers of PTR zones associated with my group, I'd like a way to hide those by default to declutter the zone list.

**Comment by nspadaccino** [comment]
I'm thinking we could add a checkbox option that would filter out all the PTR zones from the view, similar to the View Open Requests Only checkbox in the DNS Changes view. Something like this:
<img width="1680" alt="Screen Shot 2022-05-26 at 12 28 34 PM" src="https://user-images.githubusercontent.com/37352107/170532691-c1f36a0a-b27e-45b4-bc0d-fbeb3558ff9c.png">
:

**Comment by jhg03a** [comment]
PTR zones in general are a weird bird: https://github.com/vinyldns/vinyldns/discussions/1106
