### ISSUE TITLE
Portal Can not login form extended network 

### ISSUE THREAD

**Issue by thang86** [vinyldns/vinyldns#1160]
Bad Request
For request 'GET /' [Host not allowed: xxx.xxx.xx :9001]

curl -v http://localhost:9001/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 9001 (#0)
> GET / HTTP/1.1
> Host: localhost:9001
> User-Agent: curl/7.61.1
> Accept: */*
>
< HTTP/1.1 303 See Other
< Pragma: no-cache
< Expires: 0
< Location: /login?target=/
< Set-Cookie: PLAY_SESSION=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Path=/
< Set-Cookie: PLAY_FLASH=eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImFsZXJ0VHlwZSI6ImRhbmdlciIsImFsZXJ0TWVzc2FnZSI6IllvdSBhcmUgbm90IGxvZ2dlZCBpbi4gUGxlYXNlIGxvZ2luIHRvIGNvbnRpbnVlLiJ9LCJuYmYiOjE2NTkzNTE4ODcsImlhdCI6MTY1OTM1MTg4N30.Atv9MA08DsMHMnWtmMU8Si6ouavXiUNMAyl6nvjSEww; SameSite=Lax; Path=/; HTTPOnly
< Cache-Control: no-cache, no-store, must-revalidate
< Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
< X-Frame-Options: DENY
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Permitted-Cross-Domain-Policies: master-only
< Date: Mon, 01 Aug 2022 11:04:47 GMT
< Content-Length: 0
<
* Connection #0 to host localhost left intact

- Internal host ok 
- Extended form another host and how login with domain

**Comment by Jay07GIT** [comment]
This is working as expected. 

VinylDNS is a web based application. When we use [http://localhost:9001](http://localhost:9001) in browser, application will redirect to [http://localhost:9001/login](http://localhost:9001/login). When we try with CURL `curl -I http://localhost:9001`, It unable to redirect to [http://localhost:9001/login](http://localhost:9001/login) . 
```
Response: 
➜ curl -I http://localhost:9001       
HTTP/1.1 303 See Other
Pragma: no-cache
Expires: 0
Location: /login?target=/
Set-Cookie: PLAY_SESSION=; Max-Age=0; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Path=/
Set-Cookie: PLAY_FLASH=eyJhbGciOiJIUzI1NiJ9.eyJkYXRhIjp7ImFsZXJ0VHlwZSI6ImRhbmdlciIsImFsZXJ0TWVzc2FnZSI6IllvdSBhcmUgbm90IGxvZ2dlZCBpbi4gUGxlYXNlIGxvZ2luIHRvIGNvbnRpbnVlLiJ9LCJuYmYiOjE2NTk0MzIwOTQsImlhdCI6MTY1OTQzMjA5NH0.TzQ7I0kU5IZkgPDnCUxb306OlPLMqQBH-ye09gtPZuU; SameSite=Lax; Path=/; HTTPOnly
Cache-Control: no-cache, no-store, must-revalidate
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Permitted-Cross-Domain-Policies: master-only
Date: Tue, 02 Aug 2022 09:21:34 GMT
Content-Length: 0
```

Try to access the [http://localhost:9001](http://localhost:9001) in browser.
