### ISSUE TITLE
Simplify API Configuration for docker

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#123]
**Motivation**
The API Configuration is too cumbersome.  

**Scope of change**
This can be simplified by pulling out environment specific things and secrets into environment variables.

1. Update the config file in the api docker image to have environment variables for all the things.
1. Update the config file for the portal docker image to have environment variables for all the things.
1. Update the operator guide to describe the environment variables in detail
1. Update the README for the api docker image on docker hub
1. Update the README for the portal docker image on docker hub

**Comment by pauljamescleary** [comment]
This should be able to be sized.  Anything that is environment specific needs to be an environment variable.  We have maybe 20 some odd environment variables.  Gotta make the updates as mentioned in the scope of change, and add a README section on how to set them.

Things that will be environment variables include:
- sqs connection info
- dynamodb connection info
- mysql connection info
- crypto info

**Comment by pauljamescleary** [comment]
Bumping this up.  As we update our CI process, we should also review the design of our CONF and what is passed in via DOCKER.

**Comment by nspadaccino** [comment]
Resolved by https://github.com/vinyldns/vinyldns/pull/1058
Environment variables are now set in /quickstart/.env
