### ISSUE TITLE
Lock down Docker and Notary versions

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#124]
**Motivation**
Docker and Notary sometimes introduce breaking changes and the versions on a maintainers machine have to be compatible to sign images

**Scope of change**
Do some digging in the Notary repo readme, they mention this somewhere. Then in our Developers guide and Maintainers guide find where we tell people to install notary and docker, and recommend the correct version

**Comment by nimaeskandary** [comment]
We could do this in a way that we don't have to babysit the versions, maybe something like we always the latest Docker version, and the Notary version is whatever the latest is that supports it, or vice versa we could always support the latest notary, and downgrade Docker to be compatible

**Comment by pauljamescleary** [comment]
Recommend closing as we are going to change our ci/build/release process

**Comment by nspadaccino** [comment]
Fixed by https://github.com/vinyldns/vinyldns/pull/1058
Docker process has been updated, Notary is no longer required
