### ISSUE TITLE
Email Validation Regex fails if address contains - and +

### ISSUE THREAD

**Issue by pedrokiefer** [vinyldns/vinyldns#1241]
Email Validation fail if address contains `-` and `+`.

The current regex has `[a-zA-Z0-9._]+` as matching group, which makes invalid emails as `team+vinyl@domain.com` or `long-team-name@domain.com`.  Both emails are valid. 

Version: 1.18.2 and newer.

**Comment by arpit4ever** [comment]
Thank you @pedrokiefer for reporting the issue.
We will update the email validation as part next release. Few other enhancements are also in works as part of https://github.com/vinyldns/vinyldns/pull/1238

**Comment by arpit4ever** [comment]
PR https://github.com/vinyldns/vinyldns/pull/1238 merged
Fix included on [v0.18.5](https://github.com/vinyldns/vinyldns/releases/tag/v0.18.5)
