### ISSUE TITLE
Bug with accessing group changes

### ISSUE THREAD

**Issue by nspadaccino** [vinyldns/vinyldns#1269]
Certain groups display a 500 error when accessed via the portal or API. This error happens when the group contains a group change which has a user ID that is no longer in the users table. Trying to get the user which no longer exists causes a chain reaction making both the group and the particular group change inaccessible. While users should never be removed from the users table, this has happened a few times. We need to add a check in the relevant membership methods which prevents an error if a user id in the group change is not found.

**Comment by Aravindh-Raju** [comment]
To test out this issue, I created a group with two users. I deleted one of the users from `user` table. When I went to the group page, I don't see any errors. I see the deleted user as `unknown user` without facing any errors as seen below:
<img width="1904" alt="Screenshot 2023-06-27 at 3 40 53 PM" src="https://github.com/vinyldns/vinyldns/assets/61419792/7c3bf33d-01d4-4d8d-9f3c-d37eac79f1ca">

Is there a way to reproduce the error? Also, do you know how a user is deleted from `user` table? I don't see any method in our application to remove a user from the database.
