### ISSUE TITLE
Migrate modules/portal/private

### ISSUE THREAD

**Issue by mitruly** [vinyldns/vinyldns#127]
**Motivation**
According to a concern (https://github.com/vinyldns/vinyldns/pull/118#discussion_r211346982), there may be good motivation to move migrate local portal configuration settings and the `private` directory from inside `modules` to root. This is because the Docker image staging process includes the nested `conf` folder and potentially the `private` folder as well.

**Scope of change**
Move `private` folder from `modules/portal` to project root, potentially doing something similar for `modules/portal/conf`. Update the necessary configurations for the portal to continue operating correctly.

**Comment by pauljamescleary** [comment]
Unclear where this falls.  It feels like low hanging fruit and something that can easily be knocked out with the update to our CI

**Comment by nspadaccino** [comment]
All files under modules/portal/private has been moved. https://github.com/vinyldns/vinyldns/pull/1058
