### ISSUE TITLE
Portal UI Changes

### ISSUE THREAD

**Issue by Aravindh-Raju** [vinyldns/vinyldns#1280]
**Describe what you'd like to see added or improved in VinylDNS**

Proposing few new changes to the UI:
1. ManageRecords page,  Move [Page #] , next to Previous & Next buttons. This is already the case for Zones & All-Zones page.
2. ManageRecords page, move search button, search field and Filter By Record Type to Records row.
3. Zones page (zones & all-zones), move Hide PTR Zones an Search by admin group next to Zone Search button.
4. RecordSearch page, move Search field and Filters to Records row.
5. RecordSearch page, move [Page #]  next to Previous & Next.

**Comment by nspadaccino** [comment]
For the Zones search box, it seems like the search box and checkbox position change based on the size of the window.
In fullscreen before the changes it looks like this:
<img width="403" alt="Screenshot 2023-08-01 at 5 04 23 PM" src="https://github.com/vinyldns/vinyldns/assets/37352107/14ffa848-716e-44ce-b5ef-8259c7bb3b35">

In fullscreen after the changes it looks like this:
<img width="427" alt="Screenshot 2023-08-01 at 5 04 30 PM" src="https://github.com/vinyldns/vinyldns/assets/37352107/09cc252d-180e-4ad3-8204-400b79078693">

Before the changes, if I shrink the window horizontally, the search box and checkboxes look the same.

After the changes, if I shrink the window horizontally, it can look like this:
<img width="427" alt="Screenshot 2023-08-01 at 5 05 52 PM" src="https://github.com/vinyldns/vinyldns/assets/37352107/c6832bb8-3e05-4ab4-aa22-ea534b7a00dc">

Could we have the search and checkboxes inside the grey row but in the same relative positions as before?
