### ISSUE TITLE
Documentation for RecordSetCount API

### ISSUE THREAD

**Issue by arpit4ever** [vinyldns/vinyldns#1309]
Add documentation for /api/zones/:zid/recordsetcount

Feature Issue: https://github.com/vinyldns/vinyldns/issues/1244

**Comment by Jay07GIT** [comment]
Issue has been resolved. -> [Doc](https://github.com/vinyldns/vinyldns/blob/master/modules/docs/src/main/mdoc/api/get-recordset-count.md)
