### ISSUE TITLE
Zone can be created multiple times (portal)

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#131]
**Describe the bug**
When connecting to a zone, if you click the "Connect" button multiple times quickly in the dialog, the zone gets created twice.

**VinylDNS Version**
Current

**To Reproduce**
1. On the Zones tab, select "Connect"
2. Enter your zone information.  Can use a test zone like `old-vinyldns.`
3. Click "Connect" quickly
4. The zone is created twice

**Expected behavior**
The zone should be created one time.

**Comment by britneywright** [comment]
@pauljamescleary Trying to replicate this bug. Does the zone appear twice in the portal Zones page?

**Comment by nimaeskandary** [comment]
@britneywright yeah its hard to do but have had it happen to me multiple times, zone appears twice
