### ISSUE TITLE
Unsafe use of target="_blank"

### ISSUE THREAD

**Issue by mitruly** [vinyldns/vinyldns#133]
**Describe the bug**
Merely using `target="_blank"` to open a link in a new tab without correctly setting the `rel` attribute or disassociating the new window from its parent is unsafe since the child has access to the parent's `window` object (see: https://mathiasbynens.github.io/rel-noopener/; https://medium.com/@jitbit/target-blank-the-most-underestimated-vulnerability-ever-96e328301f4c).

**VinylDNS Version**
We have links such as:
```
<a href='@{link.href}' target="_blank">@{link.title}</a>
```

**Additional context**
All links that use `target="_blank"` should also have the `rel` attribute set:
`rel='noreferrer noopener'`

This resets the `opener` property, of the child window so it doesn't have access to the parent's. Both `noreferrer` (more widely supported/for older browsers) and `noopener` (for newer browser versions) should be specified.

**Comment by nimaeskandary** [comment]
Huh, nice that's good to know

**Comment by britneywright** [comment]
yeah and good examples. +1
