### ISSUE TITLE
"Setup LDAP" documentation for LDAPS improvement

### ISSUE THREAD

**Issue by Shi-Lung** [vinyldns/vinyldns#1362]
Hello,

"Considerations" paragraph for LDAPS setup is a bit vague. It says " The portal provides an option to specific a java key store when it starts up."

Could you please elaborate ? I am actually struggling to get a persistent keystore with custom root certificates with no success. What is this this option to specify the keystore ?

**Comment by Aravindh-Raju** [comment]
Hi,

The details regarding java key store can be found here:
https://github.com/vinyldns/vinyldns/tree/master/modules/portal#building-locally

We'll update the [documentation for LDAP](https://www.vinyldns.io/operator/setup-ldap.html) with the same soon.
