### ISSUE TITLE
DNS Change page not operable if there's any validation error

### ISSUE THREAD

**Issue by Aravindh-Raju** [vinyldns/vinyldns#1384]
**Describe the bug**
Please provide as much detail as you can. Here are some important details:

1. When we encounter any validation error while performing DNS Change, we would see a alert in the top denoting there are errors and will let us fix the same. But now, it just doesn't let perform any changes after the alert appears.

**Comment by arpit4ever** [comment]
PR merged. Issue not observed. 
Code will be release on v0.20.2
