### ISSUE TITLE
Alias our protoc version

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#14]
We use protoc 2.6.1 and currently instruct developers to uninstall protoc if they have it and install our version since we don't keep updated with latest. Suggesting that we have a script that installs and compiles protoc 2.6.1 to bin/protoc-2-6-1 and configure sbt to use that binary instead of the users default protoc

**Comment by pauljamescleary** [comment]
Is protoc system dependent?  Perhaps we also go back to the way things were before, where updates to the `.proto` to generate the Proto.java are done "out of the build."  I kinda don't like telling people to install this 2014 version of protoc either.

**Comment by pauljamescleary** [comment]
We are having a conversation over at #17 on this.

We may want to consider an RFC for "bring your own serializer".  Protobuf 2.6.1 was _our_ design decision.  At the time VinylDNS started, protobuf 3.0 was not a thing (or really new).

**Comment by nimaeskandary** [comment]
resolved in https://github.com/vinyldns/vinyldns/pull/113
