### ISSUE TITLE
Allow users to search for zones they do not manage

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#143]
**Is your feature request related to a problem? Please describe.**
A user only can see / search for zones that they have access to.  If a zone is registered in VinylDNS, and the user does not have access, they have no way to know it is there.

**Describe the solution you'd like**
1. Allow users to _search_ for a zone they do not have access to and have it display.  
1. User should not be able to _click_ into the zone, but just see the "summary" detail on the search result list.
1. User should see the group email in the summary detail so they can contact the owner to potentially gain access to the zone.

**Comment by britneywright** [comment]
this was resolved with #689
