### ISSUE TITLE
Cleanup syntax and helpers in unit and integration tests

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#144]
**Motivation**
The unit and integration tests heavily use `whenReady`, `CatsHelpers`, and `AkkaTestJawn`.  `CatsHelpers` and `AkkaTestJawn` overlap in functionality.  `whenReady` is no longer useful since we are using `IO` instead of `Future`.

**Scope of change**
Most of these can use `EitherMatchers` and `EitherValues`.  In addition, we should create our own custom scalatest matchers around `IO`, and delete the `AkkaTestJawn` and `CatsHelpers`.

Look at https://github.com/IronCoreLabs/cats-scalatest

**Comment by rebstar6** [comment]
note also, in a lot of cases, we are doing something like:
```
val result = IO[something].unsafeToFuture()
whenReady(result, timeout) { x => x shouldBe y }
```
We can cut out ^^ (and remove the reliance on ScalaFutures) and just make this
```
val result = IO[something].unsafeRunSync()
result shouldBe y 
```

**Comment by pauljamescleary** [comment]
Unclear on how prevalent this issue still is.  This would largely be revisited with a Scala 3 upgrade, so perhaps we just postpone?

**Comment by remerle** [comment]
Will be reviewed with #967
