### ISSUE TITLE
Move JDBC things to doobie

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#157]
**Motivation**
Currently, scalikejdbc uses "global" things like connection pools and such, so we are doing a lot of side effecting global things that get hidden from the developer.

In addition, scalikejdbc does not allow us to do for comprehensions through a transaction, and has no first class support for cats effect IO

**Scope of change**
Re-write our JDBC repositories to use [doobie](https://github.com/tpolecat/doobie)

**Comment by pauljamescleary** [comment]
This is a good idea, but should wait until Scala 3 at this point as it could be a big re-write.

Going to add a postpone on this, should consider closing

**Comment by remerle** [comment]
Closing. To be revisited as part of the overhaul incoming with #967
