### ISSUE TITLE
Fully implement the repositories for MySQL

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#16]
**Motivation**
Presently, the databases are split between MySQL and DynamoDB.  DynamoDB was originally used for scale as Comcast has 100MM records and 1MM zones.  Many potential do not need that scale.

Also, very large SQL databases can potentially handle the volume of records even at Comcast's scale.

**Approach**
1. Implement all of the `Repository` traits in MYSQL.
1. Create migration scripts to initialize the database for MYSQL for all necessary tables / columns
1. Refactor / change `JdbcXXXRepository` to `MySQLXXXRepository`

**Discussion**
1. Perhaps we move the models and repository traits into the `core` module.  This will allow us to support potentially different databases like MongoDB, Postgres, etc.

**Outcome**
1. Removed the requirement to make all this configurable, as that is being addressed in #54 .
1. Will not move the repositories yet
1. Will rename `Jdbc` things to `MySQL` things as we the SQL inside the repositories is specific to `MySQL`. 

Instead, just keep this to implementing the repositories.  We would have integration tests for the new MySQL Repositories.  Keep everything in `api` for the time being as we will be moving a lot of things out in future PRs.

**Comment by pauljamescleary** [comment]
We do need to have a mechanism to abstract away which database is used before we can do this.  Perhaps an issue to be started about moving the configuration of our databases, including the implementation type of the repository.  Similar to what we do with "Crypto".

We don't _have_ to move things to `core` as a first step; however, we _must_ make the loading of the repositories configuration driven.

**Comment by mitruly** [comment]
@pauljamescleary I fully support pluggable repositories since it also allows flexibility for other people to implement their own interfaces with databases which aren't implemented in the code.

**Comment by pauljamescleary** [comment]
I am going to create an RFC for this.  I think there are a few threads of work.

1. Create a "pluggable" mechanism whereby users can _configure_ their database.  Update `Boot.scala` to load the repos via configuration
2. Create a full MySQL repository.

**Comment by pauljamescleary** [comment]
Opened up an RFC here - https://github.com/vinyldns/vinyldns/pull/54

That one feels pretty small for an RFC.  We should be able to move on that pretty quickly once we are past this documentation.

**Comment by pauljamescleary** [comment]
Probably should move this out of discussion since the RFC is open.  We could move this forward without the RFC being merged, however noone could actually use the new repositories until it the RFC was implemented.  May want to "back burner" this for the time being, what say you?

**Comment by pauljamescleary** [comment]
Moved this to "blocked" as would like to get the RFC merged and implemented before this.  It _in theory_ can be done in parallel if anyone wants to pick it up.  Otherwise, it cannot be used until the RFC is complete.

**Comment by britneywright** [comment]
Can we close this if there's an RFC? Out of the RFC will come actionable issues right?

**Comment by pauljamescleary** [comment]
@britneywright this is orthogonal to the RFC.  tbf, we can do this work without the RFC for pluggable repos.  

The hardest part of this issue is going to be doing bulk insert of record sets and record set changes.  When we do a zone sync, we may have to bulk insert millions of record sets and record set changes.  Whoever picks up this card needs to do a little research / trial and error.

MySQL does have really good support for "bulk insert" already.

Here is a link on considerations - https://dev.mysql.com/doc/refman/5.6/en/optimizing-innodb-bulk-data-loading.html

MySQL has support for multi-row inserts 

```
INSERT INTO tbl_name (a,b,c) VALUES(1,2,3),(4,5,6),(7,8,9);
```

The only question I have is how many inserts can we do at the same time?  We have to "batch" them together.  Whoever picks up this card needs to do some calculations about how big a typical row is and what the max size is of the operation.  

There is a database benchmark RFC opened that we will be doing as well that will further optimize these bulk inserts and we can fine tune the BULK INSERT sizes for record sets and record set changes

**Comment by pauljamescleary** [comment]
+1 for me on this.  I think this can get sized and implemented.  All the repositories have simple interfaces.  The record set and record set changes are "tricky" as mentioned in my previous comment, but the exact size of a single bulk insert will be fine tuned in the database benchmark

**Comment by rebstar6** [comment]
+1 from me in that i dont know that i have much more discussion to do on this. Any cards out of this should be blocked by https://github.com/vinyldns/vinyldns/issues/103 though - once the loading framework is in place, this card is strictly implementing a list of repos

**Comment by rebstar6** [comment]
also, i would put any data migration that we may or may not do in our specific instance between dynamo and mysql into a different card.
