### ISSUE TITLE
Clean up Monitored, Instrumented

### ISSUE THREAD

**Issue by rebstar6** [vinyldns/vinyldns#167]
This is some old code that is confusing and need a rewrite. Need to look into a few things here:
1. Do we need nl.grons.metrics, or is codehale good enough?
2. Pull out the akka dependencies. the `record` method is only used in the directives, that should be split out.
3. We probably dont need Monitor classes (or the Monitor object). The MetricsRegistry is doing a getOrAdd behind the scenes anyway, so it should be fine to just call some of this stuff directly.

**Comment by pauljamescleary** [comment]
We definitely need a fresh approach to metrics.  

Recommend closing with a postpone, as this can be revisited when we go to Scala 3.  Dropping in good tracing / logging / monitored is under consideration for that effort

**Comment by remerle** [comment]
Closing.  To be revisited as part of the overhaul incoming with #967
