### ISSUE TITLE
Do not require protoc to be installed on a developer's machine

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#17]
**Motivation**
Adding proto compilation to the build process has the following drawbacks:

1. Developers have to install some really old version of protoc on their environment
1. The build takes longer as travis has to download and install protoc on every build

**Scope of change**
1. Have a developer compile the proto java file and stash it into src/main/java
1. Update the docs

The downside is that anyone who wants to add to .proto is going to have to install protoc and update the file.  That happens rather infrequently compared to builds that happen all the time.

**Comment by nimaeskandary** [comment]
👍 I like this more, seems needless to add the extra time to our builds. Do we need to have some sort of verification to make sure whoever updated the file did it correctly? The protobuf diffs are too crazy to review

**Comment by pauljamescleary** [comment]
Part of this story will be:

- [ ] Create a bash script that compiles the proto file
- [ ] The script should create the file in `modules/api/src/main/java/vinyldns/proto/VinylDNSProto.java`
- [ ] If the file exists, overwrite the file
- [ ] Update the README and add remove the protoc requirement
- [ ] Add a section to the DEVELOPER guide mentioning that "if you need to modify the proto, then you have to install this version of protobuf and then run this script

**Comment by pauljamescleary** [comment]
Going to wait until @rebstar6 has time to chime in, leaving in discussion for a few more days.

**Comment by pauljamescleary** [comment]
Or use this!!!!

https://github.com/thesamet/sbt-protoc

**Comment by pauljamescleary** [comment]
It does appear as though sbt-protoc allow people to work WITHOUT protoc installed.  I could not get sbt-protoc to work, didn't try very hard though.  It looked as though it was compiling our proto to version 3, but of course we are on version 2.
