### ISSUE TITLE
Update group feature in portal

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#171]
**Is your feature request related to a problem? Please describe.**
The api has an update group endpoint but it is not integrated with the web client

**Describe the solution you'd like**
Add a tab on the groups page in the portal with a form to update a group 

**Describe alternatives you've considered**
People can use other VinylDNS clients like the ruby client to hit that endpoint, but since the portal is the flagship client it should probably implement that feature too

**Comment by pauljamescleary** [comment]
This is just portal work, as the API is already available
