### ISSUE TITLE
Renew credentials in the portal

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#18]
**Motivation**
If a user's credentials are compromised, currently there is no mechanism to update credentials without directly going into the database and making a change manually.

**Proposal**
* In the user drop down in the upper right hand corner of the portal, add an option to "Renew Credentials".  This should generate a new access key and secret, and update the user table with the new keys so they can immediately be used.
* Warn the user before submitting, as credential change could be destructive for automation users.
* Log a change in the audit table that the credentials have been changed

**Comment by nimaeskandary** [comment]
Think this should be a post for security reasons as well, ensures the csrf header has to be sent with the request
