### ISSUE TITLE
Clean up dynamodb module testing

### ISSUE THREAD

**Issue by rebstar6** [vinyldns/vinyldns#182]
**Motivation**
There's a lot of duplication between the unit and integration specs in this module, which makes maintaining the code tough.

**Scope of change**
- Review all the unit and integration specs in dynamoDb. Where there are duplicate tests, keep the integration spec version
- If there are database calls that do not have integration specs, write them!
- Note: it's ok if some unit tests remain where they are testing logic confined to a specific method.

**Comment by pauljamescleary** [comment]
Recommending we delete dynamodb all together.  This should be closed

**Comment by remerle** [comment]
This is obsoleted by #971
