### ISSUE TITLE
Delete DynamoDB Groups

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#189]
**Motivation**
Currently, we are not deleting groups from DynamoDB, we are just marking them as "Deleted".  The issue is that we are repeatedly running black box tests creating and deleting groups.  Overtime, these unused "deleted" groups will impact query performance and table cost.

**Scope of change**
Delete groups when they are deleted.

**Comment by rebstar6** [comment]
closing for https://github.com/vinyldns/vinyldns/issues/311
