### ISSUE TITLE
Blacklisting records

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#233]
**Background**
When considering "shared zones", there maybe certain records that zone or vinyldns admins do not want to allow open access to.  These typically are "high value domains" that should never change without strict authorization.

**Requirements**
1. The system should allow vinyldns admins or zone admins to create a blacklist of records that cannot be modified (are locked down).
2. The blacklist will exist _per zone_.  
3. The records that are blacklisted cannot be modified via VinylDNS.  They can only be updated out-of-band.
4. A blacklist entry consists of an FQDN and optional list of record types.  If the record type is empty, then _all_ record types for that FQDN are considered black listed.  For example `www.foo.com A` would lock down any operation on `A` records only; whereas, `www.foo.com [empty]` sould lock down any operation on `ALL` records.
5. VinylDNS admins (super users) have the ability to override and change any blacklisted domain in the system.  VinylDNS will warn before allowing modification to blacklisted domains.

**Proposed Design**
1. Add a section to `Manage Zone` or a new tab that allows zone admins or vinyldns admins the ability to manage the black listed records for their zone
2. Allow the user to designate blacklisted records when they connect to a zone
3. The blacklist should live with the existing `zone` endpoints, as additional data on the `zone` entity itself.

**Note: We could simply add new ACL access entry for "blacklist".  Allows the user to just create an ACL Rule that says "blacklist www.foo.com".**

**Questions**
1. Should we maintain a separate, "global" black list that only vinyldns admins can maintain (or perhaps live in configuration so it is hard to get to)?  Just thinking that we wouldn't want someone to accidentally "un-blacklist" www.comcast.net for example.
**Answered: Yes, we should have a global black list.**

**Comment by rebstar6** [comment]
Do we want this to be all on fqdns? feels like regex's could be useful (and not much added effort).

Also, is there anything "high value" in reverse? and IPs that have to be locked to changes?

**Comment by rebstar6** [comment]
Also, should definitely discuss phasing this - is a global blacklist sufficient to start? There are larger discussions to be had around an admin interface, but it is easy enough to get a global blacklist in config. If that covers most of our use, would be awesome to be able to prioritize that and move onto some other things before revisiting an admin interface and per-zone blacklist

**Comment by pauljamescleary** [comment]
@rebstar6 I think a global blacklist will be sufficient to start.  However, I think that "High Value Domains" #254 is a higher priority than this issue.  

We separated these two out recently:
1. High Value Domains will never be managed through VinylDNS.  That is a global blacklist
2. Blacklist would support "VinylDNS Admin" override.

I think explicitly restricting updates to certain records is valuable from a product feature perspective, but may even be out of scope for MVP

**Comment by nspadaccino** [comment]
Closing, will log a new issue if this feature becomes requested
