### ISSUE TITLE
Use ip4s for CIDR and IP validating

### ISSUE THREAD

**Issue by rebstar6** [vinyldns/vinyldns#235]
https://github.com/Comcast/ip4s

This is something we could use both for our CIDR rules logic, as well as for any ip validations we do, which is awesome. Some thoughts on where:

- A record data should be IPv4 type
- AAAA record data should be IPv6 type
- Batch PTR input should be IPAddress
- Look at ReverseZoneHelpers file for misc cidr things (classless reverse zone delegations, and ACL rules use these)

Scope of this card includes:
- Remove dependency on orchard CIDR library, use ip4s, make all tests pass.
- Replace validations with ip4s where needed
- Check the portal, there may be no changes there

**Comment by pauljamescleary** [comment]
Hundo-P - we should normalize on IP4S, we are already using it in most places and should do it in other places as well.  Rather low hanging fruit, could touch a fair bit of code, shouldn't be too complex
