### ISSUE TITLE
Allow ACL rules for any group

### ISSUE THREAD

**Issue by rebstar6** [vinyldns/vinyldns#237]
Zone admins are able to add ACL rules on groups to grant them limited access within a zone. However, they are only allowed to add an ACL rule for groups they are a member of, which is limiting.

We should:
- Remove the restriction that the user be in the group the ACL is being created for
- In the portal, update the groups selection in the ACL rule form to display as free text (a dropdown will be too big). Autocomplete would be ideal if possible.

**Comment by britneywright** [comment]
We should break this one down

**Comment by djvl** [comment]
Hi, is there any progress on this issue?

**Comment by pauljamescleary** [comment]
@djvl not yet, we can prioritize this.  Is this holding you up?

Let us know if you can give some color as to how this issue is impacting you, that would be useful for prioritzation :)

**Comment by jhg03a** [comment]
I'd add to this that it may not just be zone admins wanting to modify ACLs, but also record owners.  This also would include the ability to transfer record ownership from one group directly to another.

**Comment by remerle** [comment]
I know that there is a new portal in the works (#968), but this seems like a limiting feature that may make sense to take care of.

**Comment by remerle** [comment]
Fixed by #1127

**Comment by remerle** [comment]
Only took four years! 🎉
