### ISSUE TITLE
Use super user status in the portal

### ISSUE THREAD

**Issue by rebstar6** [vinyldns/vinyldns#238]
Throughout the portal, we rely on group membership to determine what someone has access to. For super users, getMyGroups returns all groups, so this works, however it is slow (all the groups in the system are returned!). From auth, we know that a user is a super user. Given that, we should bypass the getMyGroups call and resulting logic, and jump to showing the data or page involved.

Specifically, see the determineAdmin function in controller.records.js, and review the getMyGroups calls in the zones pages.

**Comment by britneywright** [comment]
We're now doing something like that in the batch change detail page of the portal https://github.com/vinyldns/vinyldns/blob/master/modules/portal/app/views/batchChanges/batchChangeDetail.scala.html#L1 

related controller https://github.com/vinyldns/vinyldns/blob/master/modules/portal/app/controllers/FrontendController.scala#L81-L87

we could probably expand that use and cut down on the group checks.

**Comment by nspadaccino** [comment]
Closing, addressed by the portal overhaul https://github.com/vinyldns/vinyldns/issues/968
The portal has been updated extensively since this issue has been raised
