### ISSUE TITLE
Set scalac compiler flag for fatal warnings

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#24]
**Motivation**
We do not fail compile if any of our compiler flags warn.  This causes failures during PR builds that could have been resolved locally.

**Scope of change**
Add `"-Xfatal-warnings"` to our compiler options.

**Comment by kevinmeredith** [comment]
Perhaps it's worthwhile to extend this issue's scope to use https://github.com/DavidGregory084/sbt-tpolecat? What do you think?

**Comment by pauljamescleary** [comment]
@kevinmeredith that sounds like a good idea.  Most of our `CompilerOptions` are pulled from tpolecat's recommendations.

If you are willing, would gladly take a PR?

A few things to consider that really should be fixed, but are a little beyond simple:

1. The core module currently has a `NoOpCrypto` that takes a config that is not used that will fail.  We currently in the build filter that out.  Hopefully we can still do the same with that plugin?
2. The portal module really should have a limited set of compiler flags.  It was poorly maintained and would like to ideally overhaul the portal (scalajs? http4s?).  I would be curious how many of those flags would work.

**Comment by pauljamescleary** [comment]
Let's evaluate if the plugin is suitable, i.e. there aren't _tons_ of warnings.  Otherwise, let's for the scope of this issue just flip fatal on.

**Comment by pauljamescleary** [comment]
@kevinmeredith had 200 some odd errors on just normal compile, forget about test compile.

Some of those errors should probably be fixed, but will be a little bigger of a cleanup effort.

Moving forward with the `fatal` for the time being.

Thanks for the recommendation!  The plugin just dropped in and worked.

**Comment by kevinmeredith** [comment]
Glad to hear and thanks, Paul! I hope to contribute to this library at some point.
