### ISSUE TITLE
Add tests for portal controller VinylDNS.scala

### ISSUE THREAD

**Issue by britneywright** [vinyldns/vinyldns#245]
This work can be broken down into multiple PR's. If submitting a PR for this issue, please specify the scope of work completed in the PR description.

**Motivation**
We have a lot of untested functions in the VinylDNS controller. Code coverage is currently turned off for those functions, but when it's on our code coverage drops to around 59% for the file. We want full test coverage so future changes to the codebase don't cause issues without us realizing it.  

**Scope of change**
Note: All of the functions are already tested for the custom action in them (userAction, or frontEndAction). 

Functions with coverage turned off:
- getZones
- getZone
- syncZone
- getRecordSets
- listRecordSetChanges
- addZone
- updateZone
- addRecordSet
- deleteZone
- updateRecordSet
- deleteRecordSet

**To test locally**
After writing the tests in VinylDNSSpec:
- remove the `// $COVERAGE-OFF$` and `// $COVERAGE-ON$` where applicable
- in the terminal run `sbt ";project portal;coverage;test;coverageReport"`
- this will generate a local report that you can view in the browser. The html file path will appear towards the end of the terminal output, you can copy and paste it in the browser to review the code coverage changes.

**Comment by remerle** [comment]
This should be handled as part of #968
