### ISSUE TITLE
High Value Domains

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#254]
**Is your feature request related to a problem? Please describe.**
We need to support the idea of "blacklists", at a global level and a zone level.  However, there are instances where you don't want anyone to ever modify certain domains.

**Describe the solution you'd like**
Allow admins to configure a list of high value domains.  These domains should _never_ be managed through VinylDNS.  All attempts, even super users, should be prevented to make any changes to these DNS records.

It maybe sufficient to have this just be configuration driven initially until we have an "Admin" section of VinylDNS.

**Design**
1. Add a config section called "high-value-domains".  Have it be a list of FQDN based regular expressions.
1. Add a validation for any record update.  If the record fqdn (record label + zone name) is a high value domain, immediately reject.  This should just be in `RecordSetValidations` and `BatchChangeValidations`
1. Be sure to call the new `isHighValueDomain` for all adds, creates, deletes in the `RecordSetService`and `BatchChangeService`

**Comment by nimaeskandary** [comment]
Is there the possibility of high value reverse zone names? @pauljamescleary @rebstar6

**Comment by rebstar6** [comment]
yes. should be logically the same, will just be a regex
