### ISSUE TITLE
Use official docker image for func tests

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#26]
**Motivation**
Currently for `bin/func-test-api.sh` and `docker/docker-compose-func-test.yml`, the api is started up from a fat jar. This can be updated to use the official api docker image.

**Scope of change**
- `docker/docker-compose-func-test.yml` will have to be updated to pull the api image, this can copy `docker/docker-compose-build.yml`
- update `bin/func-test-api.sh` to not create the api fat jar

**Comment by pauljamescleary** [comment]
Should postpone this until our own deployment uses the docker images, need to push to get that done in short order.

**Comment by pauljamescleary** [comment]
This is more or less blocked.  We are converting our run-time environment to docker.  Once that is stood up, we should be able to do that.  Need a "remindme" bot

**Comment by nimaeskandary** [comment]
@pauljamescleary any news on our run-time environment being converted to docker? Would nice to get rid off all the old stuff in `bin/` that's not docker related

**Comment by pauljamescleary** [comment]
Recommend closing as we are going to change our ci/build/release process
