### ISSUE TITLE
Fix docs links for single changes

### ISSUE THREAD

**Issue by rebstar6** [vinyldns/vinyldns#263]
The links for SingleAddChange or a SingleDeleteChange are broken at https://www.vinyldns.io/api/get-batchchange.html#http-response-attributes-

They should be updated to point to https://www.vinyldns.io/api/batchchange-model.html#singleaddchange-attributes and https://www.vinyldns.io/api/batchchange-model.html#singledeletechange-

The updates need to be made in this file in order to post to the docs: https://github.com/vinyldns/vinyldns/blob/master/modules/docs/src/main/tut/api/get-batchchange.md#http-response-attributes-

**Comment by RupeshGoud** [comment]
Hello there! I would like to help you with that, could I?

**Comment by rebstar6** [comment]
@RupeshGoud looks like we already have a PR on this - this issue is still open though https://github.com/vinyldns/vinyldns/issues/260, and is a similar docs fix (maybe a little more typing, but not crazy) if youre interested!
