### ISSUE TITLE
Handle duplicate records for record sets consistently

### ISSUE THREAD

**Issue by mitruly** [vinyldns/vinyldns#266]
**Motivation**
Currently batch requests consolidate duplicate records for a record set, while the record set service itself does not. We need to be consistent with how we handle record sets with duplicate records, while being cognizant of handling backwards compatibility for existing record sets.

**Scope of change**
There are potentially two directions that we can take:
- Allow duplicate records for a `RecordSet` within a batch change request.
  - Simpler approach that maintains backwards compatibility.
- Consolidate duplicate records for `RecordSet`.
  - Involves a major upgrade and clean up of older records.
  - Reduces clutter (eg. adding a duplicate record to an existing `RecordSet` would be disallowed since it would be the same change).

**Comment by pauljamescleary** [comment]
This feels edge casey to me, right @mitruly ?  If so, I would think we would just collapse duplicate records by doing a `.distinct` on them on the way into the app (JSON, Protobuf, DNS).  Although I doubt they would never be duplicate coming from DNS.

I do question the prevalence of the issue.

**Comment by pauljamescleary** [comment]
Not sure what to do with this one, not many have brought this up so I lean toward postpone+close

**Comment by nspadaccino** [comment]
Similar to this issue https://github.com/vinyldns/vinyldns/issues/1139
Resolved in https://github.com/vinyldns/vinyldns/pull/1144
