### ISSUE TITLE
Docs typo: SSHFP record model docs cite a `typ` attribute

### ISSUE THREAD

**Issue by mdb** [vinyldns/vinyldns#268]
**Describe the bug**

It appears the record set model docs for SSHFP records cite a `typ` attribute. I believe this is a typo and should be `type`.

**VinylDNS Version**

`master` documentation

**To Reproduce**
1. Go to the [record set model docs](https://www.vinyldns.io/api/recordset-model.html)
2. View the [record set data info associated with SSHFP record sets](https://www.vinyldns.io/api/recordset-model.html#record-data-information-)
3. Note that it cites a `typ` attribute

**Expected behavior**
I believe the attribute should be `type`.

**Additional context**
This was pointed out to me [here](https://github.com/vinyldns/vinyldns-cli/pull/19) by @tenpaiyomi.

**Comment by pauljamescleary** [comment]
Is this closed?  @mdb, @nimaeskandary ?

**Comment by mdb** [comment]
@pauljamescleary Yes, I believe this is fixed, as PR #269 has been merged.
