### ISSUE TITLE
docker-up-vinyldns.sh fails to reliably start VinylDNS services

### ISSUE THREAD

**Issue by mdb** [vinyldns/vinyldns#270]
**Describe the bug**

`bin/docker-up-vinyldns.sh` frequently fails to start VinylDNS services.

**VinylDNS Version**

`master`

**To Reproduce**
1. Run `bin/docker-up-vinyldns.sh` from within the root of the `vinyldns` repository
2. Observe that the script frequently exits with messages such as `Exceeded retries waiting for VinylDNS API to be ready, failing`.

**Expected behavior**
I would expect `bin/docker-up-vinyldns.sh` to reliably start VinylDNS services.

**Stack trace or error log output**

```
bin/docker-up-vinyldns.sh
Starting portal server and all dependencies in the background...
Creating network "docker_default" with the default driver
Creating vinyldns-bind9     ... done
Creating vinyldns-dynamodb  ... done
Creating vinyldns-mysql     ... done
Creating vinyldns-elasticmq ... done
Creating vinyldns-api       ... done
Creating vinyldns-portal    ... done
Waiting for API to be ready at http://localhost:9000 ...
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Retrying Again
Exceeded retries waiting for VinylDNS API to be ready, failing
```

**Additional context**
I have observed this problem on my local Macbook Pro, as well as in TravisCI.

**Comment by nimaeskandary** [comment]
Hm, we set that retry with all the vinyl devs pretty much using the same machines, we could increase the retry another minute or two to accommodate for other machines. 

Could also add an arg variable to override timeout?

**Comment by pauljamescleary** [comment]
Right, I think increasing the timeout should be fine.  We have to wait for mysql to start up, then run our migrations (which run on an empty environment), and finally wait for the app to start up which itself takes time (akka-http most of it).

**Comment by pauljamescleary** [comment]
The change here is to edit the `bin/docker-up-vinyldns.sh` script, and change the `RETRY=40` to `RETRY=60` in two places.

**Comment by mdb** [comment]
I am re-opening this issue, as it seems I'm not having difficulty reliably running VinyLDNS in TravisCI, even when using the `--timeout=120` flag: 

https://travis-ci.org/vinyldns/go-vinyldns/jobs/448542183

In conversation about this, @rebstar6 pointed out that it's arguably unnecessary to start both the API server and the portal for running my `vinyldns/go-vinyldns` integration tests; just the API should suffice. However, it appears there's no easy way to run a local Dockerized API server in absence of the portal, as `docker-up-api-server.sh` expects a local VinylDNS build & `jar` file. She suggested changing `docker-up-api.sh` to `docker-up-api-local.sh` and creating a `docker-up-api.sh` that functions similar to `docker-up-vinyldns.sh` but starts just the API.

**Comment by nimaeskandary** [comment]
The problem is we bind `docker/portal/application.conf` to the portal image in our docker compose file, and we have been changing that up since publishing the image in ways that are no longer compatible. Will just remove that conf because really the portal image can just use the default that is packaged in there

**Comment by mdb** [comment]
@nimaeskandary I see. I did also create PR #318 , though I can see you may have a preferable solution in mind.

**Comment by nimaeskandary** [comment]
@mdb Will try to kill two birds with one stone and fix this issue, and allow for you to just start up the api if you want

**Comment by mdb** [comment]
That'd be great -- thanks @nimaeskandary !

**Comment by nimaeskandary** [comment]
@mdb @NorseGaud a fix for this was just merged. Also allows you start up the `docker-up-vinyldns.sh` script without the portal using the --api-only flag
