### ISSUE TITLE
Break up build.sbt

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#286]
**Motivation**
We have many modules and many settings, build.sbt is getting cluttered

**Scope of change**
Break up module specific settings and add additional settings files to the modules themselves

**Comment by beatriz** [comment]
I could take a try at this, any additional guidelines or I'll start at it and ask if something comes up?

**Comment by remerle** [comment]
Not a priority right now. We'll clean this up as part of #967
