### ISSUE TITLE
Remove implementation-specific information from monitoring

### ISSUE THREAD

**Issue by mitruly** [vinyldns/vinyldns#289]
**Motivation**
To keep monitoring information implementation-independent.

**Scope of change**
Currently endpoint and Dynamo information has non-implementation info in the monitoring (eg. `repo.UserChange.save`, `Endpoint.listGroupAdmins`, etc.), but MySQL and SQS modules do. Remove implementation-specific info from monitoring.

Find `monitor` usages in the codebase.  `queue.SQS.xxx` should just be `queue.xxx` as an example

**Comment by remerle** [comment]
Let's revisit as part of #967
