### ISSUE TITLE
Look into gitter bot or hook for pr notifications

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#3]
Can we get notifications in gitter for prs and stuff?

**Comment by nimaeskandary** [comment]
Looks like it is built in to gitter, if you go to the room on the right under the list of members there is an activity section, where it has an option for a github intergration

**Comment by britneywright** [comment]
Hmm I selected the github integration but it said bad request. I think gitter is trying to use github services still, but that's deprecated. looking into it more.

**Comment by britneywright** [comment]
Think i was able to setup a webhook manually.
