### ISSUE TITLE
Remove machine specific creds file from build.sbt

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#302]
**Motivation**
Currently sonatype settings in build.sbt use this line to get credentials:

```credentials += Credentials(Path.userHome / ".sbt" / "1.0" / "vinyldns-gpg-credentials")```

This could be removed and we could expect creds to be in global settings @ `~/.sbt/1.0/credentials.sbt`

This would reduce sbt warnings on machines that don't have `vinyldns-gpg-credentials`

**Scope of change**
* Remove `credentials += Credentials(Path.userHome / ".sbt" / "1.0" / "vinyldns-gpg-credentials")` from build.sbt
* Update MAINTAINERS.md, in the section that talks about where to put sonatype creds, these should be put in `~/.sbt/1.0/credentials.sbt` now

**Comment by remerle** [comment]
No longer an issue - the code mentioned no longer exists.
