### ISSUE TITLE
Add delete function to GroupRepository trait

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#311]
**Motivation**
Due to legacy logic groups are not deleted from the DynamoDBGroupRepository, but instead have their status set to `Deleted`. This could be changed, and the groups can now be deleted.

**Scope of change**
* GroupRepository trait should have a `def delete(group: Group): IO[Group]`
* Delete group implementation in DynamoDBGroupRepository
* consider what indexes are needed by DynamoDBGroupRepository if status is not longer used, potentially make a new card for this
* Refactor how group deletions are done in the route

**Comment by pauljamescleary** [comment]
This is done, closing
