### ISSUE TITLE
Add health checks for DynamoDB, SQS

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#313]
**Background**
Presently, we only health check that we can talk to MySQL.  This is done via the `/health` HealthRoute.  We will not be system aware of an outage on other dependencies.

**Solution**
Use drop wizard metrics health checking to check all dependencies.  This should be in the module itself (MySQL, DynamoDB).

Will need to add LDAP authentication checks to the portal.

**Notes**
https://metrics.dropwizard.io/3.1.0/manual/healthchecks/

If we run health checks on demand (by the Load Balancer), it maybe too frequent.

I would recommend having a daemon service that polls those health checks once every few seconds, and have the `HealthRoute` just ping that daemon.  Can use FS2 and things like `Ref` for concurrently setting and fetching state.

**Comment by rebstar6** [comment]
#325 did databases, working on queues now
