### ISSUE TITLE
Group and Zone visibility for things you're not in

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#320]
**Is your feature request related to a problem? Please describe.**
A user may want to join or create group that already exists, know the group but not who is in it to request access, not be able to connect to a zone and would want to know the current admin group, etc

**Describe the solution you'd like**
If it is not a security vulnerability, may be nice to see admin groups of zones you try to connect to but they are already taken, and to be able to search for groups you are not in and at least see group managers to request to be added

**Comment by britneywright** [comment]
This is broken down into issues #642, #643, #645, #646
