### ISSUE TITLE
Shared Zones support

### ISSUE THREAD

**Issue by rebstar6** [vinyldns/vinyldns#346]
Epic tracking shared zones related cards

RFC: https://github.com/vinyldns/rfcs/blob/master/text/0002-shared-zones.md

**Comment by nimaeskandary** [comment]
Note, a group can be deleted though it is set to be the owner of recordsets. For now we are allowing this, and future updates to those recordsets must change the owner group if it no longer exists

**Comment by britneywright** [comment]
can we close this epic?
