### ISSUE TITLE
Allow super users to update a zone to shared (or unshared)

### ISSUE THREAD

**Issue by rebstar6** [vinyldns/vinyldns#348]
Similar logically to #345 

For now, this functionality is super user only.

See `ZoneInput` type in #345. Make update zone endpoint take in that type.

Logically, need to compare old with new `shared` field. If None is passed in, keep old `shared`. If something is passed in and its different than the old status, fail for normal user, succeed for super user.

---
similarly, this is hard to func test, but can validate that a normal user can not update a non-shared zone to be shared.

**Comment by mitruly** [comment]
`ZoneSerializer.fromJson` can also be removed once update is implemented.
