### ISSUE TITLE
Add page title and site description metadata in portal for social media

### ISSUE THREAD

**Issue by britneywright** [vinyldns/vinyldns#36]
**Is your feature request related to a problem? Please describe.**
No meta data appears when sharing the portal login page.

**Describe the solution you'd like**
Title and description at least, maybe logo but not really necessary. Probably same title and description across the site. title: `VinylDNS - whatever page is being linked` description: `DNS Management Platform`.

**Additional context**
example in Slack for reference of how the metadata is used:
<img width="624" alt="screen shot 2018-08-01 at 10 25 55 am" src="https://user-images.githubusercontent.com/4439228/43527760-52763918-9575-11e8-8172-e9366e48e902.png">

**Comment by pauljamescleary** [comment]
This sounds good, is this ready to be worked on @britneywright ?

Also, maybe a "good for first timers"?

**Comment by britneywright** [comment]
Slack has a good blog post about unfurling URLs and what metadata they look at: https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254

We'll want to use a combination of Facebook open graph tags and Twitter card tags. 

This anchor link goes right to a good example in the article: https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254#ef6c

Here's what I think we'd probably look to put in the metadata. May need to add some configuration values and assign variables in views to be picked up in the main page layout.

```
<!-— facebook open graph tags -->
<meta property="og:type" content="website" />
<meta property="og:url" content="[CONFIG DOMAIN VALUE]/[PATH]" />
<meta property="og:title" content="[CONFIG SITE TITLE VALUE]" />
<meta property="og:description" content="[PAGE SPECIFIC DESCRIPTION]" />
<meta property="og:image" content="[VINYLDNS LOGO]" />
 
<!-— twitter card tags additive with the og: tags -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:domain" value="[CONFIG DOMAIN VALUE]" />
<meta name="twitter:title" value="[CONFIG SITE TITLE VALUE]" />
<meta name="twitter:description" value="[PAGE SPECIFIC DESCRIPTION]" />
<meta name="twitter:image" content="[VINYLDNS LOGO]" />
<meta name="twitter:url" value="[CONFIG DOMAIN VALUE]/[PATH]" />
```
