### ISSUE TITLE
Add test flag to block test users from shared zones

### ISSUE THREAD

**Issue by rebstar6** [vinyldns/vinyldns#364]
With shared zone support, our test users (along with all normal users), would have access to all the shared zones in the system. We really only want them to have access to the test shared zones.

To accomplish this, should create some kind of test flag on users and zones. If a recordset change is made, and the user is a test user, the change should only go through if the zone is flagged as a test zone. This applies in batch and the regular recordset endpoints

---

EDIT: this is the full scope of this card:
- add test flag on users
- add a test flag on zones
- disallow recordset edits (batch or in zone) by test users in non-test zones

there will be a followup to address a load endpoint

**Comment by rebstar6** [comment]
Here's what im thinking:
- add test flag on users
- add a test flag on zones
- disallow recordset edits (batch or in zone) by test users in non-test zones
- add an endpoint to load the test data. This will load users and optionally some groups and zones. the shared zones will have to be loaded in this way, normal zones can be loaded with either. at least one group will have to exist in this endpoint in order to load the zone (for the admin group)

for now:
- dont think we need any changes to groups. the test flag on the user should stop changes from going through anyway
- dont think we need changes to zone edits: shared zones cant be edited by anyone outside of the admin group. so long as our test users are not in our shared zones groups, this is fine

**Comment by rebstar6** [comment]
we can potentially limit this further and still preload the zone without an endpoint (add a group and zone in TestDataLoader)

**Comment by mitruly** [comment]
I'm on-board with most of these points. Regarding the endpoint to load the test data - is there specific data/request types that we are supporting? I'm kind of leaning toward the approach of using a TestDataLoader and not using an endpoint.

**Comment by rebstar6** [comment]
updating the details for this card to include the above in the loader. can followup with an endpoint later
