### ISSUE TITLE
Publish api and portal docker images to docker hub

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#37]
**Motivation**
Need to be able to publish our api and portal images to hub.docker.com/vinyldns

**Scope of change**
Content trust should be enabled, more details can be found here: https://docs.docker.com/engine/security/trust/content_trust/

Care should be taken that when creating keys for the content trust signing process, that they are securely stored

There should be a process for publishing images to docker hub, including bumping the version number of our images. This will likely have to be done with first a pr to update build.sbt, as the version seems to be immutable

**Comment by pauljamescleary** [comment]
Blocking until we have a strategy for managing the secrets that is more robust than having them on a single developer's machine
