### ISSUE TITLE
Clean up Maintainer Guide

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#370]
**Motivation**
The Maintainer Guide for setting up docker and sonatype have could be made easier to follow, and optionally one or more scripts could be made to do most of the work

**Scope of change**
In the sonatype steps, you can't import the key in step 10 without reading the passphrase in step 12, these are out of order

Create a script that walks a user through setting up sonatype

Create a script that walks a user through setting up notary

**Comment by pauljamescleary** [comment]
This should be done when the CI/Release process is updated.  Bump

**Comment by nspadaccino** [comment]
Has been addressed by https://github.com/vinyldns/vinyldns/pull/1058
sonatype has been replaced with concourse ci
