### ISSUE TITLE
GET /not-supported returns unauthorized

### ISSUE THREAD

**Issue by rebstar6** [vinyldns/vinyldns#388]
**Describe the bug**
Go to `/not-here` in the api - it is passing along to our authorization as if this is an authorized route, and you get a 401 with `Authentication Failed: Authorization header not found`

This should respond with whatever the default not found is for akka http (404?), and the request should not be passed along to the AuthPrinciple logic

**Comment by britneywright** [comment]
Is this still an issue? I get a 404 when testing this.

**Comment by pauljamescleary** [comment]
Yes, I am getting the following still

```
< HTTP/1.1 401 Unauthorized
...
Authentication Failed: Authorization header not found
```

**Comment by pauljamescleary** [comment]
I think this should be a 405 to be honest

**Comment by britneywright** [comment]
I've looked into this before, I believe the part I'm stuck on is the order of the routing. We have initial routes that don't require authentication, then routes that do require authentication. Any route that isn't found is falling into the authentication umbrella
