### ISSUE TITLE
Stale operator guide docs regarding databases

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#389]
**Describe the bug**
Operator guide info is stale, should be noted that all databases can be implemented in MySql 

additionally, MySql can be used as an option for the queue. 

Refer to https://github.com/vinyldns/vinyldns-python/blob/master/docker/conf/application.conf for an example config with mysql enabled for the databases and queue

**VinylDNS Version**
0.8.0

**To Reproduce**
1. Go to 'https://www.vinyldns.io/operator/pre#database

**Comment by rebstar6** [comment]
migration link in https://www.vinyldns.io/operator/setup-mysql is broken too, should link to https://github.com/vinyldns/vinyldns/tree/master/modules/mysql/src/main/resources/db/migration
