### ISSUE TITLE
beef up `bin/release.sh`

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#401]
**Motivation**
The release script only lets you do one workflow 

**Scope of change**
Few things that could be improved:

* choose to only do sonatype
* choose only api or portal docker deployment
* make sure latest tag is updated with docker on non snapshot
* theres a sbt-release setting to turn off the autocommits it does, use that for snapshots
* prob should turn off sbt-release's commit tagging, github autotags when we do a release anyway

**Comment by pauljamescleary** [comment]
Agreed, let's keep an eye on this when we update CI / release process. It should be super easy to release.

**Comment by nspadaccino** [comment]
CI has been moved to concourse, this can be closed
Resolved by https://github.com/vinyldns/vinyldns/pull/1058
