### ISSUE TITLE
put docker creds in default sbt creds file

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#402]
**Motivation**
sbt won't give users errors for non-existent cred files 

reference this: https://github.com/vinyldns/vinyldns/issues/302, and the first pr addressing it: https://github.com/vinyldns/vinyldns/pull/306

**Scope of change**
Add docker creds to a file thats imported into the default sbt creds file. This will be tricky because the docker creds have to fall under `sbt project/docker:<command>`, https://github.com/vinyldns/vinyldns/pull/306 experiments with this nesting in the comments

**Comment by pauljamescleary** [comment]
Recommend closing as we revamp CI / release

**Comment by remerle** [comment]
To be addressed as part of #972
