### ISSUE TITLE
Ignore secret in ZoneConnection keys when stringifying

### ISSUE THREAD

**Issue by mitruly** [vinyldns/vinyldns#408]
**Motivation**
Sensitive connection information should be masked in the logs. Currently `ZoneConnection` doesn't have an override `toString` method to encrypt the connection information, so printing either the `ZoneConnection` or `Zone` in logs will store the keys.

**Scope of change**
One approach could be to associate a cryptography with the ZoneConnection and override the `toString` method.

Another, simpler approach, is to just remove the key information.

---
Edit: Should override toString in ZoneConnection to print name/keyName/primaryServer. Omit key. See toString override in Zone for example. Validate that Zone toString has the connection in this format.

**Comment by pauljamescleary** [comment]
Is this still an issue?  If so, this is a fast one to implement.  Look at ZoneConnection and make sure that we have an override on `toString` sounds simple enough to prevent accidental logging of sensitive info
