### ISSUE TITLE
Better groups control

### ISSUE THREAD

**Issue by rebstar6** [vinyldns/vinyldns#415]
We are using a groups dropdown in the following locations:

- Manage Zone - zone admin group dropdown
- Manage Zone - add ACL rule modal (ACL for group)
- [Coming Soon] New Batch Change (see https://github.com/vinyldns/vinyldns/issues/343)

This is not a great interface for super users (all groups in the system), or the ACL dropdown, which should be expanded to allow any group to be entered. 

We should have a new groups form fill option that will autocomplete to any group in the system. We should use this field for super users in all 3 locations, and other users in the ACL modal.

Note: the field is optional, so may be left empty, on the new batch change screen. Other 2 places it's required.

**Comment by remerle** [comment]
We should address this as part of #968

**Comment by nspadaccino** [comment]
Addressed in portal overhaul https://github.com/vinyldns/vinyldns/issues/968
