### ISSUE TITLE
Allow free form record search across zones

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#428]
**Is your feature request related to a problem? Please describe.**
When you have access to a lot of zones, you may not necessarily know off the top of your head which zone a record belongs to.  It becomes cumbersome to go into each zone you have access to, run a record search, find nothing, repeat.

**Describe the solution you'd like**
Provide a record search screen that allows users to free form search for records by record name across zones.

1. Provide a new record search screen that allows users to do a record search
2. Allow free form record search in the API, a new endpoint for the search
3. Allow users to further filter their results by record type, including one or more record types to include in their results

**Comment by britneywright** [comment]
Is the intention to restrict this to only records the user has access to?

**Comment by pauljamescleary** [comment]
Closing this as complete
