### ISSUE TITLE
RFC Guide

### ISSUE THREAD

**Issue by britneywright** [vinyldns/vinyldns#43]
- [x] What is an RFC and why are we using it in VInylDNS
- [x] VinylDNS RFC process
- [x] example RFC

**Comment by pauljamescleary** [comment]
I created https://github.com/vinyldns/rfcs

A lot of people plagerize RUST, found dozens of them, so I followed suit.

**Comment by pauljamescleary** [comment]
I checked off the example, as we have 2 "real" RFCs now underway.  I think this is done.
