### ISSUE TITLE
Build out release process

### ISSUE THREAD

**Issue by mitruly** [vinyldns/vinyldns#46]
**Motivation**
We want to have a smooth release process that is capable of auto-versioning and publishing/releasing both Scala artifacts and Docker images.

**Scope of change**
- Configure `sbt-release` to perform auto-versioning
- Support overriding default configuration with passed-in parameters
- Integrate docker publish with `sbt`

**Comment by pauljamescleary** [comment]
Moving this to prioritized, as this represents more-or-less the "last" of the post-opensource things we have to do.
