### ISSUE TITLE
Replace await with IO

### ISSUE THREAD

**Issue by mitruly** [vinyldns/vinyldns#464]
**Motivation**
Recently there have been some transient failures in our unit tests where the result of `await`/`awaitResultOf` will fail with a `None.get` exception. These should be replaceable using the Cats `IO` library, as we've switched over.

**Scope of change**
Corresponding unit tests will have to get updated, and potentially remove deprecated functions from `CatsHelpers.scala`.

**Comment by pauljamescleary** [comment]
This is definitely something that should no longer exist.  Easy enough fix as it impacts tests only, but we really should NEVER use `await` anywhere including tests.
