### ISSUE TITLE
Large record data can look strange in the UI

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#477]
![image](https://user-images.githubusercontent.com/17361753/52350515-c5477900-29f6-11e9-8f59-9a93f40b9408.png)

To replicate:
- In the portal, make a new record in a zone with long record data. Probably best to make a TXT record type with record data that is 256 characters (the maximum allowed).

To fix:
This may be resolved by restricting the width of the Record Data column and wrapping the text. Open to other suggestions to handle displaying the long data. The table is found in `modules/portal/views/zones/zoneTabs/manageRecords.scala.html`

**Comment by pauljamescleary** [comment]
Oof, unsure how to wrap that but we should wrap if possible.

We may want to consider elipses --to--> popup for more info (expand / collapse), something along those lines

**Comment by britneywright** [comment]
@pauljamescleary i implemented wrapping in the PR #637
