### ISSUE TITLE
Spruce up API documentation

### ISSUE THREAD

**Issue by mitruly** [vinyldns/vinyldns#478]
**Motivation**
Currently, we have API documentation for users to reference, but there may be some stale information such as missing parameters, outdated fields.

**Scope of change**
- API calls that take in query parameters need to be updated with the corresponding information
- Any changes in our API request/response data models need to be reflected

**Comment by britneywright** [comment]
@mitruly do you have specifics for this issue or can we close this in favor of more specific issues?

**Comment by nspadaccino** [comment]
Api docs have been updated at https://www.vinyldns.io/api/
