### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by mitruly** [vinyldns/vinyldns#5]
Configure Travis to manage continuous integration.

Required task list:
- [x] Verify API tests
- [x] Verify API functional tests
- [x] Verify API integration tests
- [x] Verify portal grunt tests
- [x] Verify portal functional tests
- [x] Implement code coverage
- [x] Publish documentation microsite on PR merge

Extras:
- [x] Caching
- [x] Parallel tasks grouped (by stages)

**Comment by britneywright** [comment]
We should also add the Travis badge to the Readme once it's setup. I believe it's https://img.shields.io/travis/vinyldns/vinyldns/master.svg.

**Comment by britneywright** [comment]
will this also include the publishing of the docsite, or should we put that in a separate issue?

**Comment by mitruly** [comment]
@britneywright Updated issue task list to include microsite publishing.

**Comment by pauljamescleary** [comment]
@mitruly Microsite publishing would be on merge to master, right?  We wouldn't do that on PR builds.

**Comment by mitruly** [comment]
@pauljamescleary Yes, that's a good point. I have updated the issue task list to reflect this.
