### ISSUE TITLE
Add Sort feature in Record Table columns

### ISSUE THREAD

**Issue by jbollineni** [vinyldns/vinyldns#541]
**Is your feature request related to a problem? Please describe.**
I'm unable to sort columns in a zone's Records table. All entries get sorted by the their name, by default.

**Describe the solution you'd like**
Add a sort feature to each column in the table

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by britneywright** [comment]
@jbollineni sorting by record data might be tricky since that data varies. but sorting by ttl and record type seems straightforward.

**Comment by kontrolldkaos** [comment]
I think this feature request is a needed one. By record type is definitely useful. Another thing I think would be useful is to separate the apex data into a separate tab.

**Comment by nimaeskandary** [comment]
@kontrolldkaos Could definitely see it being useful. The SQL query for paging through record sets will need to be updated on whether it should go after a specific type here https://github.com/vinyldns/vinyldns/blob/master/modules/mysql/src/main/scala/vinyldns/mysql/repository/MySqlRecordSetRepository.scala#L187

Can you elaborate on the apex data being a separate tab? By that do you mean a tab where you only view apex records? We currently allow you to search by name so a user could search for the zone apex
