### ISSUE TITLE
Implement RFC 8567

### ISSUE THREAD

**Issue by trevmex** [vinyldns/vinyldns#564]
Maintaining high Quality of Experience (QoE) increasingly requires end-to-end, holistic network management, including managed Customer Premises Equipment (CPE).  Because customer management is a shared global responsibility, the Domain Name System (DNS) provides an ideal existing infrastructure for maintaining authoritative customer information that must be readily, reliably, and publicly accessible.

VinylDNS clearly needs to support this useful and revolutionary new standard. :)

**Comment by pauljamescleary** [comment]
I read this as @trevmex is going to implement RFC 8567 ;)

Am I reading this right (I am new to this RFC) that sensitive data like logins and credit cards are stored in clear text in DNS?

https://tools.ietf.org/html/rfc8567#section-2.1

**Comment by pauljamescleary** [comment]
@trevmex Ahh, the April Fool's RFC for 2019.  Well played sir.
