### ISSUE TITLE
Replace `Future` with cats effect `IO`

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#60]
**Motivation**
Future has a lot of drawbacks, including:

1. Profiling futures can be difficult as the `onComplete` is scheduled as a task on a thread pool
1. _Everything_ is queued, even tasks that we know are sequential or have to block
1. Because everything is queued, the potential exists for overrunning HEAP
1. They can cause sporadic failures in unit and integration tests in the event that timeouts occur

**Scope of change**
Replace all `Future` with `IO`.  This effectively touches a lot of the codebase.

There is a `Result` type alias that is pervasive.  Changing that from `EitherT[Future, Throwable, A]` to `EitherT[IO, Throwable, A]` should take care a lot of the changes.

All `Repository` and `Service` should work off `IO`

All `DnsConnection` should work off `IO`

There is an `IO` shim in the `engine` presently to pull `Futures` through to `IO`.  That can be deleted once everything is moved.

`akka-http` requires `Future`, that should be the only place in the code where we convert to `IO`.  Would be great if there was some kind of first class support for `IO` in akka-http.

**Comment by mitruly** [comment]
I'm not overly familiar with the differences between `Future` and `IO`, so this seems to be a good summary. The proposed changes make sense to me.

There was one item that I had a question about: 
> Everything is queued, even tasks that we know are sequential or have to block

Is it possible to group synchronous tasks together in to a single queued task, or would that be too tedious and more easily implemented in `IO`?

**Comment by pauljamescleary** [comment]
@mitruly with Future, we do a lot of for comprehensions which are by their nature sequential (the next task does not start until the previous task completes.  Here is a snippet from the `RecordSetService`...

```scala
  def deleteRecordSet(
      recordSetId: String,
      zoneId: String,
      auth: AuthPrincipal): Result[ZoneCommandResult] =
    for {
      zone <- getZone(zoneId)
      existing <- getRecordSet(recordSetId, zone)
      _ <- canDeleteRecordSet(auth, existing.name, existing.typ, zone).toResult
      _ <- notPending(existing).toResult
      _ <- typeSpecificDeleteValidations(existing, zone).toResult
      change <- RecordSetChange.forDelete(existing, zone, Some(auth)).toResult
      send <- commandBus.sendZoneCommand(change)
    } yield send
```

The second line `getRecordSet` does not _start_ until `getZone` completes.  So effectively, this is a sequential process, so there is no need for all of this to be in a `Future` at all.

There are times when we do want to _explicitly_ do things as `async`, and then `join` them together when _both_ are complete (or something failed).  `IO` supports this use case as well.

Not sure if I answered your question.  But the `queue` comment I made was unless you use `Future.successful` (which is a lie and not a good idea), every one of those above statements is run in a separate execution context, on a separate thread, and the current thread blocks waiting for the other thread to complete.  In the sample that is a waste, since the process is synchronous by its nature.

**Comment by rebstar6** [comment]
Look at BatchChangeInterfaces.scala too - BatchResult type change there should cover a lot of that chunk of code.

Overall this makes sense, may want to split it up into different cards for different pieces of the codebase if possible.

**Comment by mitruly** [comment]
@pauljamescleary Thank you for the response - the info in the last bit answered my question. Definitely makes sense to avoid this when possible.

@rebstar6 I agree that partitioning the changes would make reviewing and converting the code base easier to stomach. Would it make sense to partition by our file grouping or maybe type of change?

**Comment by pauljamescleary** [comment]
tbh, this is smaller in scope than the scalaz --> cats conversion.  I think it can stay as one issue, and perhaps a few PRs go in.

The main design question is around things that actually are parallelized, like how to do that properly.  There is treatment on that in the cats-effect documentation on `join` but that pattern has not been established.  I am going to ping Pilquist to see if he can give us a pattern on parallelizing IO

**Comment by pauljamescleary** [comment]
An example of parallelizing in Future is as follows...

```scala
val f1 = Future(Thread.sleep(500); println("done1"))
val f2 = Future(Thread.sleep(500); println("done2"))

for { 
  a <- f1
  b <- f2
} yield ()
```

**Comment by rebstar6** [comment]
probably worth as a team doing a quick session together on IO. I've been looking into it a little for my current card, but understanding when to use `IO()` vs `IO.pure()` vs `IO.async()` vs whatever else would be super helpful for all of us to be on the same page on

**Comment by rebstar6** [comment]
lol i guess the "I am going to ping Pilquist" handles that comment. seconding your comment PJ :)

**Comment by pauljamescleary** [comment]
Talked to Pilquist about this.

Also I encourage everyone to review this document.  We can review as a team as well - https://typelevel.org/cats-effect/datatypes/io.html

In a nutshell, should always use `IO.apply`, i.e. `IO(my function here)`.  

Really should avoid `IO.pure` unless we are trying to inject a value into a suspended computation.  They give examples like `IO.pure(25).flatMap(v => println(v))` or something similar.

Can use things like `IO.pure` for unit tests when working with constant values.

Use `MonadError` for errors, specifically `IO.raiseError` to raise an error.

Most of our stuff is in `Result`, which will become `EitherT[IO, Throwable, A]`

For anything that _must_ happen concurrently, he recommended the newer `par` combinators like `parSequence`, `parTupled`, `parMapN`.  We have relatively few places in the code where we do that.

There is also en example in the docs of `retry` loop.  We have at least one place where we retry, we can just follow that example.

**Comment by pauljamescleary** [comment]
Giving this the old +1
