### ISSUE TITLE
Quick search/filter zones by Admin Group, Email, Status, etc.

### ISSUE THREAD

**Issue by daveback** [vinyldns/vinyldns#602]
As an administrator with the ability to see a very large quantity of zones, I am looking for the ability to search through zones (in the Zones view) using fields other than the zone name itself.  The ability to filter by Admin Group is desired, in particular.

The quick search box in the top right is clear and effective, and fulfilling this request could possibly involve having that search box to say "keyword" instead of "zone name" -- and then having it search and identify any lines with that keyword in it, period.

An addition suggestion would be having the keyword highlighted in the filtered results.  I would consider that part optional and not truly in scope for this request.

**Comment by nimaeskandary** [comment]
Hi Dave, thanks for the suggestion! I agree that more powerful searching would be useful for Administrators. The way the listing of zones is done from the API is that we fetch a max page of 100 items at a time, and the client keeps track of nextIds for paging. So noting if done we will have to build out more search query strings into the API endpoint, and alter our SQL query for zone listing
