### ISSUE TITLE
Ability to search/filter Groups by keyword

### ISSUE THREAD

**Issue by daveback** [vinyldns/vinyldns#603]
As an administrator, I am looking for the ability to keyword search/filter the list of groups in the Groups view.  (Similar to how the search in the Zones view functions.)

An additional suggestion would be having the keyword highlighted in the filtered results. I would consider that part optional and not truly in scope for this request.

**Comment by nimaeskandary** [comment]
Noting we can close if https://github.com/vinyldns/vinyldns/pull/621 is merged

**Comment by britneywright** [comment]
Also noting that a current workaround is using the in-browser search functionality since we currently return all groups on the groups page

**Comment by remerle** [comment]
We should address this as part of #968
