### ISSUE TITLE
Cannot manage DS records in the portal

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#605]
**Describe the bug**
DS records appear in the portal if they exist, but one cannot create, update, or delete them

**VinylDNS Version**
0.9.0

**Expected behavior**
1. I can create, update, or delete a DS record set

**Comment by nimaeskandary** [comment]
@pauljamescleary would this be better classified as a feature request?

**Comment by pauljamescleary** [comment]
I understand we pushed this off for other priorities, but now it is inconsistent and since we have other VinylDNS users these days I am going to keep it as a bug.  Should be a small fix we can get in as part of our normal bug squashing.
