### ISSUE TITLE
All completed Zone Changes are saved with the status "Synced"

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#618]
**Describe the bug**
In the ZoneChangeHandler, a completed zone change is saved with the status "Synced". This doesn't seem intuitive since we also have an unused "Complete" status. Think we should decide on if we want to use that status or remove it 

**VinylDNS Version**
0.9.2-SNAPSHOT

**Comment by britneywright** [comment]
we should probably remove "Complete"
