### ISSUE TITLE
Capture `405` in access logs

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#62]
**Describe the bug**
If a URL request is made that does not match a valid endpoint, we are not seemingly logging the 405 in the general access log.

**VinylDNS Version**
Latest

**To Reproduce**
1. Make any request against the API that is not valid, for example `GET /foo`
2. The API returns a 405, which is correct
3. Look at the log output, no log is made on the invalid request

**Expected behavior**
A log entry should be made indicating the PATH that was requested

**Screenshots**

**Stack trace or error log output**

**Additional context**

**Comment by nimaeskandary** [comment]
addressed in https://github.com/vinyldns/vinyldns/pull/508
