### ISSUE TITLE
Deprecate support user

### ISSUE THREAD

**Issue by britneywright** [vinyldns/vinyldns#641]
**Motivation**
We created a support user with the intention of allowing more access than a regular user (#74), but less access than a super user. Essentially read-only access of all groups, zones and records. We plan to open the read-only access to all users and we've reduced some of the super user abilities so we no longer have a need for the support user role.

**Scope of change**
- GET endpoints
- database
- tests in the api and portal

**Comment by pauljamescleary** [comment]
Closing as duplicate of #953
