### ISSUE TITLE
Allow all users to see any existing zone

### ISSUE THREAD

**Issue by britneywright** [vinyldns/vinyldns#643]
**Is your feature request related to a problem? Please describe.**
We want to open up read-only access of data in VinylDNS. This scope of this card is limited to individual zones. A separate card will be created for the list zones endpoint.

**Describe the solution you'd like**
Allow any user to see any existing zone they request. They should not be able to update or delete the zone.

**Additional context**
I believe the endpoints this effects are:

- get zone by ID
- get zone by Name
- list zone changes

we may want to include and return an access level check that notes if the requesting user is a super user, zone admin, has ACL rule access, or none.

**Comment by jhg03a** [comment]
As a user I should always be able to resolve a User or Group ID for recordsets to which I can edit.  this includes if the group or user is deleted.  In particular this applied to IDs found on Zone / RecordSet, and Record Change.

**Comment by remerle** [comment]
We can enhance the zone view as part of Portal 2.0.  We have a global record search that provides read-only access to existing zones

**Comment by remerle** [comment]
Seems related to #641.  If we already have read-only support, then we're just making all users "support users"?  May be interesting to see how much effort this really is.

**Comment by remerle** [comment]
This can help us now as we need to work around this limitation by assigning ourselves to the owner group temporarily, then making the mod.

Marking as `ready`
