### ISSUE TITLE
Allow super users to update record owner group

### ISSUE THREAD

**Issue by britneywright** [vinyldns/vinyldns#644]
**Is your feature request related to a problem? Please describe.**
We restricted super users' ability to modify records in zones where they are not in the owner group. We do want to allow super users the ability to assign records to owner groups though.

**Describe the solution you'd like**
Allow a super user to update a record if the only change is the record owner group. They do not have to be a member of the owner group they are assigning to.

**Additional context**

**Comment by remerle** [comment]
This can help us now as we need to work around this limitation by assigning ourselves to the owner group temporarily, then making the mod.

Marking as `ready`
