### ISSUE TITLE
READMEs for Docker repositories  

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#65]
**Motivation**
People don't have information on the project from Docker hub

**Scope of change**
If you take a look at our Docker repositories on hub, for example, https://hub.docker.com/r/vinyldns/api/, the readme section is blank. We should have some information there, such as configuration values to set and volume mounts to work with the image, or at least document all that in the core project repo and link out to that

**Comment by pauljamescleary** [comment]
Moving this to prioritized.  We should be able to copy 🍝 from our existing docs where we describe docker image usage.
