### ISSUE TITLE
Zone search needs to add a trailing dot

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#652]
**Describe the bug**
Searching for the zone "foo.com" brings up nothing you need to search "foo.com.

**VinylDNS Version**
0.9.2

**Additional context**
Pay special attention to the wildcard being added. If they add a wildcard to the end of the query, then dont add

**Comment by britneywright** [comment]
This is a result of changes implemented https://github.com/vinyldns/vinyldns/pull/636
