### ISSUE TITLE
Consistent paging nextId when table is empty

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#660]
**Motivation**
This came up in https://github.com/vinyldns/vinyldns/pull/640#discussion_r286585404. Making a card for discussion. Gist is, not all paging functions, between all our repos and dynamo vs sql, return None if you end right on the table boundary and you will page an empty page for the last one

My viewpoints are this doesn't really matter, as clients will get an empty list and a nextId of None for the next one, so don't see it breaking anything

**Scope of change**
All paging implementations could do a lookahead of one, and decide if the nextId is needed

**Comment by nspadaccino** [comment]
Resolved in https://github.com/vinyldns/vinyldns/pull/694
