### ISSUE TITLE
Pull API images from Docker Hub

### ISSUE THREAD

**Issue by mitruly** [vinyldns/vinyldns#69]
**Motivation**
Instead of relying on a fat `.jar` for running the API, we can now use image hosted on Docker Hub (at https://hub.docker.com/r/vinyldns/api/tags/).

**Scope of change**
Update local and Travis-based API functional test scripts to use hosted Docker image. Use strict versioning (as opposed to `latest`).

**Comment by pauljamescleary** [comment]
Duplicates #26
