### ISSUE TITLE
Setup documentation site

### ISSUE THREAD

**Issue by britneywright** [vinyldns/vinyldns#7]
- [x] Make gh-pages branch
- [x] Add custom domain
- [x] Configure custom domain

**Comment by pauljamescleary** [comment]
Let's figure out the directory structure and different docs.  In theory we can just have "Documentation".  I like the idea of separating out "API docs" as they have a different target audience.

Brainstorming / looking for feedback...

* Documentation
    * Quick Start
    * System Architecture
    * Operator Guide (includes installing)
    * User Guide
* API Documentation
    * Authentication
    * <rest of the stuff

**Comment by britneywright** [comment]
this was just the initial setup which is done. we should make new issues for other documentation work.
