### ISSUE TITLE
Update verbiage and docs around "Zone already exists"

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#79]
**Motivation**
Presently, when a user attempts to connect to a new zone that already exists in VinylDNS, we return a message with "Zone already exists."  This is confusing to end users.

**Recommendation**
1. Update the message returned from the API server to say "The zone xxx is already registered in VinylDNS.  

If the user just does not have access, add to the return message...

```
The zone admin group is yyy.  Please contact <group name> <group email> for access to the zone.
```

It is possible that the user does have access, just is not in view.  If so, then add to the return message...

```
The zone can be found by entering <zone name here> in the search field.
```

2. Update the FAQ with information on what to do when that message is received.

**Comment by britneywright** [comment]
For the contact message can we use the designated group email address instead of admin user names?

**Comment by pauljamescleary** [comment]
@britneywright that is a better idea, I will amend

**Comment by britneywright** [comment]
I made a tweak to the message when a user is connected to a zone but doesn't see it. I think this is good to go.

**Comment by rebstar6** [comment]
easy enough, i think this one can be move to a normal card

**Comment by pauljamescleary** [comment]
This is in the `ZoneService`.

Unfortunately, the only thing in scope when that validation runs is the `zone` itself.

In order to display the group name and group email, we would have to summon the group for the zone into context.  In short, this is a little more than a "first issue"
