### ISSUE TITLE
Implement backoff+retry for each phase of record change handling

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#842]
### Background
The `RecordSetChangeHandler` is the state machine "engine" that processes validated requests that are queued for processing. There are two targets for improvement, but the design will focus on implementing retry with backoff:
1. Retry change when receiving "recoverable" DNS error responses from DNS backend: when applying the requested change, we interpret any type of error including `SocketTimeout`, `TryAgain`, `Refused`, `ServerFailure` and `DnsFailure` as immediate stops and return a failure response back to the user. We should relax our constraints and retry given certain DNS responses.
~2. Our retry policy when verifying that a change has been made: We currently verify whether a change has successfully completed, retrying the query every 500ms up to a total of 10 times (for a total of 5s) before responding to the user. Taking traffic into account, we should realistically be re-queuing the request with an increased retry timeout to free up resources for a new change.~

### Current process flow
![Current Record Set Change Handler](https://user-images.githubusercontent.com/12224090/65985554-0beb5700-e450-11e9-865a-c6372327ae6f.png)

Currently, the `RecordSetChangeHandler` follows the current process flow to process successfully validated requests:
1. Fetch a change request from the message queue.

1. `Validate` that the change has not yet been implemented by querying the DNS backend
  - If the change has _already_ been implemented, indicate `AlreadyApplied` and return with a successful response.
  - If the state of the record is in good shape (i.e. no conflict with the proposed request), indicate `ReadyToApply` and move on to `Apply` step.
  - If there are conflicting issues with the request and state of the DNS backend (e.g. create request for a record that already exists in the DNS backend, delete request for a record that does not exist in the DNS backend, update request has existing records as exact match against DNS backend), return a `Failure` response back to the user.

1. `Apply` the requested change to the DNS backend
  - If there are any errors, indicate that the request completed with a failure.
  - If there are no errors, indicate that the request has been `Applied` and proceed to the `Verify` step.

1. `Verify` that the requested change was applied to the DNS backend
  - If the change has been applied, return a successful response to the user.
  - If the change has not yet been applied, retry query every 500ms up to a total of 10 times. If change still has not been applied after retries have been exhausted, return a failure response.
  - If there is a failure response, bubble it back to the user.

### Proposed process flow
![Improved Record Set Change Handler](https://user-images.githubusercontent.com/12224090/65983687-1b68a100-e44c-11e9-82c4-37440aba1281.png)
1. Fetch a change request from the message queue. If the change has exceeded the maximum retry count, remove the change from the queue and return a failure response back to the user. Otherwise, proceed to the `Validate` step.

1. `Validate` that the change has not yet been implemented by querying the DNS backend
  - If the change has _already_ been implemented, indicate `AlreadyApplied` and return with a successful response
  - If the state of the record is in good shape (i.e. no conflict with the proposed request), indicate `ReadyToApply` and move on to `Apply` step.
  - If there are conflicting issues with the request and state of the DNS backend (e.g. create request for a record that already exists in the DNS backend, delete request for a record that does not exist in the DNS backend, update request has existing records as exact match against DNS backend), return a `Failure` response back to the user. _Also_, if the request is out or retries, return an out-of-retries failure response back to the user.
- If there are recoverable errors or any IO exceptions, increase retry counter for message and re-queue.

1. `Apply` the requested change to the DNS backend
  - If there are any unrecoverable errors (eg. SRVFAIL, etc), indicate that the request completed with a failure.
  - If there are recoverable errors or any IO exceptions, increase retry counter for message and re-queue.
  - If there are no errors, indicate that the request has been `Applied` and proceed to the `Verify` step.

1. `Verify` that the requested change was applied to the DNS backend
  - If the change has been applied, return a successful response to the user and delete the message from the queue.
  - If the change has not yet been applied, increase the retry counter and re-queue.
  - If there is an unrecoverable DNS error response, bubble it back to the user and delete the message from the queue.

Note: The `Validate`-`Apply`-`Verify` steps are collectively a higher-order function that will be retried in its entirety.

#### Add retry to apply step with exponential backoff
We can have a retry loop similar to the existing `Verify` step where we are retrying DNS changes when receiving recoverable DNS error responses. Updating the retry policies to use exponential backoff would achieve the same desired behavior. However, this adds more potential for resources to get tied up.

#### Delegate retry policy to message queue
We can simplify the retry counts by relying on the queue retry policy. However, 1. the queue implementation being used is not guaranteed to support automatic retry/dead-letter, and 2. we would have to poll the dead-letter queue to send back failure responses to the user. The trade-off is not worthwhile.

### Summary
With the new design considerations, we are increasing the success rate of VinylDNS processing against the DNS backend due to 1. scenarios in which we are reattempting DNS changes and 2. the span of time across the DNS reattempts are being retried. We are also freeing up resources to process queued messages (rather than suspending threads waiting for retry timeouts).

The main compelling reason the proposed design, is that there shouldn't be an issue attempting to reapply a change.

#### Update VinylDNS responses
Currently there are two `DnsConnection` operations that interact with the DNS backend:
- `applyChange`: attempts to apply the change to DNS backend. Possible values include: `NOERROR`, `FORMERR`, `SERVFAIL`, `NXDOMAIN`, `NOTIMP`, `REFUSED`, `YXDOMAIN`, `YXRRSET`, `NXRRSET`, `NOTAUTH`, `NOTZONE`, `BADVERS`, `BADSIG`, `BADKEY`, `BADTIME`, `BADMODE`

- `resolve`: queries the backend for a DNS record response. Possible values include: `SUCCESSFUL`, `UNRECOVERABLE`, `TRY_AGAIN`, `HOST_NOT_FOUND`, `TYPE_NOT_FOUND`

We need to introduce new wrapper error classes rather than just using a "catch-all" for `Throwable`:
```
sealed abstract class ApplyChangeError(cause: Throwable) extends Throwable(cause)
final case class UnrecoverableApplyChangeError(cause: Throwable) extends ApplyChangeError(cause)
final case class RecoverableApplyChangeError(cause: Throwable) extends ApplyChangeError(cause)

sealed abstract class ResolutionError(cause: Throwable) extends Throwable(cause)
final case class UnrecoverableResolutionError(cause: Throwable) extends ResolutionError(cause)
final case class RecoverableResolutionError(cause: Throwable) extends ResolutionError(cause)
```

#### Update `MySqlMessageQueue`
We currently hard-code `100` value for the maximum retry attempts. This needs to be configurable.

#### Update the RecordSetChangeHandler finite-state machine (fsm)
`RecoverableApplyChangeError`s: `REFUSED`
`RecoverableResolutionError`s: `TRY_AGAIN`

In `RecordSetChangeHandler`, update the fsm to:
- Re-queue the message if a recoverable error is encountered _or_ there is a failure with the promise (i.e. `IO`). If there is no retry count attribute on the message, we should assume that this is the first `attempt` and set the new `attempts` value to 2.
- Remove message from the queue during fetch stage if `attempts` count > maximum retries.

New outcomes need to be added for the FSM result:
- `Succeeded`: Remove message from queue and return good response to the user
- `Failed`: Remove message from queue and return bad response to the user
- `Retry`: Do nothing

**Comment by pauljamescleary** [comment]
@mitruly the SQS queue already has a visibility timeout of 30 seconds iirc.  So, if we just let it retry (i.e. do nothing), then it will retry roughly every 30 seconds 100 times.  I don't think we need to backoff in this case at all, as that is a total execution loop of 3000 seconds, or almost an hour.  If we cannot process it in an hour, we have to bail.

So, following your approach, you would be very detailed / explicit on which errors warrant retry, and which errors would warrant failure.  `SocketTimeout` would obviously be a retry, whereas `NotAuthorized` should be a hard stop.  Deciding which error is in which bucket is paramount to this solution.

Also, keep in mind we could fail in `Validate` as well, all three steps need to follow the solution

**Comment by mitruly** [comment]
@pauljamescleary the default visibility timeout is 30 seconds when the message is pulled. Currently there is no "releasing" of tasks to retry later; we just block on the `verify` step. The proposal is to increase the retry timeout with each allowable retry condition, with the visibility timeout slightly increasing each time.

We _could_ do what you suggest in terms of using the default value, but 1. different instances may configure different values for default visibility timeout and 2. in a retry step that was only taking 500ms between attempts, we're introducing 29.5 seconds delay for most scenarios where a second reattempt will be successful.

I will update this with allowable retry responses from the DNS backend.

**Comment by pauljamescleary** [comment]
@mitruly I was confused, I thought this was going the re-queue route.

If you want to do exponential backoff, it must be on each step (validate, apply, verify).  For example, we could get a `SocketTimeout` on any step due to a network blip, we would want to backoff/retry in that scenario.

An alternative is to just backoff / retry the entire thing, like a higher-order function between the FS2 stream and the actual handler.  This would account for a temp-down condition on the database which is invoked as part of change processing.  The 3 step process is designed for idempotency, so it may simplify the design+code to put it in a higher order function.

For any solution, we need to be very detailed about which errors warrant a retry (e.g. SocketTimeout) and which errors do not (e.g. NotAuthorized).  A simple ADT for capturing which errors warrant retry could simplify the design...

```scala
sealed abstract class(cause: Throwable) RecordChangeError extends Throwable(cause)
final case class Unrecoverable(cause: Throwable) extends RecordChangeError(cause)
final case class Recoverable(cause: Throwable) extends RecordChangeError(cause)
```

The `RecordSetChangeHandler.apply` could then be wrapped up with a HOF that could do the backoff/retry.  Anyway, food for thought.
