### ISSUE TITLE
Increase length of DNS Change review comment

### ISSUE THREAD

**Issue by mitruly** [vinyldns/vinyldns#844]
Screen capture of current review comment field:
<img width="1421" alt="vinyldns_batch_change_rejection_comment" src="https://user-images.githubusercontent.com/12224090/65707633-f1ce0500-e05a-11e9-879b-2580247f51d0.png">

This should be lengthened, preferably to the size of our description field.

Note: In order to navigate to this screen, you will have to:
1. First submit a DNS change for a non-existent zone
2. Log into the portal as a VinylDNS system admin
3. View the DNS change

-----
Good candidates for files to change:
- Increasing size of box: `batchChangeDetail.scala.html`

**Comment by ericcheatham** [comment]
If nobody else is committed to this I can take a look. If there is something else you think I’d be helpful with I can take a look at that instead

**Comment by mitruly** [comment]
@ericcheatham we can assign this to you if you're interested :) There are other issues available depending on your interests that we've pre-labeled with `Hacktoberfest`: https://github.com/vinyldns/vinyldns/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest

**Comment by ericcheatham** [comment]
Sounds good. I'll take this one and see what's next. :) 

Thanks for being amazing, y'all

**Comment by ericcheatham** [comment]
@mitruly  Sorry for the delay on this. Got a few moments to take a look (finally). I think know what I need to do to make this change but I'm not entirely sure how to build and test this particular thing. Looking at the testing instructions looks like it's hitting a pre-built docker container and not my local version.

**Comment by britneywright** [comment]
@ericcheatham are you still working on this issue?

**Comment by pauljamescleary** [comment]
Closing this as completed
