### ISSUE TITLE
Improve PTR record data validations to require fully-qualified domain name (FQDN) as target

### ISSUE THREAD

**Issue by mitruly** [vinyldns/vinyldns#845]
VinylDNS does not support relative references and PTR record data should be dotted so we know that it is not a relative reference.

Example:
```
foo.bar.       A           1.1.1.1
baz.bar.      CNAME foo
```

`baz.bar.` is attempting to be a relative reference to the existing `foo.bar.` record.

------
Good candidate files for changes:
- Update record data validations: `BatchChangeValidations.scala`
- Add unit tests: `BatchChangeValidationsSpec.scala`
- Add end-to-end tests: `create_batch_change_test.py`

**Comment by nspadaccino** [comment]
PTR records now require record data to be filled out to be added, no record data results in a `Record data is required!` message on the portal. Closing this issue
