### ISSUE TITLE
Rename "batch change" files to "dns change"

### ISSUE THREAD

**Issue by mitruly** [vinyldns/vinyldns#847]
We have recently renamed our "batch change" to "DNS Change" in the portal UI. To be consistent, we should also rename the Javascript and HTML files.

-----
Good candidate files for changes:
- `/modules/portal/public/lib/batch-change` directory and included files
- `/modules/portal/app/views/batchChanges` directory and included files

**Comment by ericcheatham** [comment]
@mitruly I can take a look at this if you'd like.

**Comment by mitruly** [comment]
That'd be awesome, @ericcheatham!

**Comment by ericcheatham** [comment]
@mitruly Is the scope of this change limited only to renaming the files or is renaming classes and things also part of this?

**Comment by mitruly** [comment]
@ericcheatham this _should_ be mainly for renaming the (portal) files unless we missed something in the code. Note that the API feature and endpoint calls are still "batch change" (which we intend to keep).

This is primarily for the portal UI.

**Comment by ericcheatham** [comment]
@mitruly Sounds good. Thanks!
