### ISSUE TITLE
Validate CNAME alias doesn't allow forward slashes for forward zones

### ISSUE THREAD

**Issue by mitruly** [vinyldns/vinyldns#849]
We currently use the same validation regex for host names that we do for input names as we do CNAME data (including allowing of `/`). The issue is that only CNAMEs in reverse zones (e.g. zones in the form of `x.x.x.in-addr.arpa.` or `x.x.x.x.ip6.arpa.`) should be allowed to have `/`; forward slashes should not be allowed in forward zones.

-----
Good candidate files for changes:
- Update validations: `BatchChangeValidations.scala` and `RecordSetValidations`
- Add unit tests: `BatchChangeValidationsSpec.scala`
- Add end-to-end tests: `create_batch_change_test.py`

**Comment by marcosbaesse** [comment]
I am currently creating a PR for this

**Comment by pauljamescleary** [comment]
Thanks!!

**Comment by remerle** [comment]
We should look at properly supporting classless delegation, not just tweaking the validation.

https://tools.ietf.org/html/rfc2317
