### ISSUE TITLE
When filtering on "View Open Requests", paging is lost

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#851]
**Describe the bug**
In the VinylDNS Portal, when filtering on "View Open Requests Only", paging is lost.

**VinylDNS Version**
0.9.3

**To Reproduce**
1. Go to `DNS Changes` in the UI Portal
2. Click on `All Requests` (assuming you have more than 100 requests in the system
3. Click on `View Open Requests Only` checkbox
4. Paging disappears

**Expected behavior**
I can still page through only open changes.

**Screenshots**

**Before clicking**

![image](https://user-images.githubusercontent.com/17361753/65781497-ae869b80-e119-11e9-817b-039b896d9e81.png)

**AFTER clicking - notice the Next button disappears**

![image](https://user-images.githubusercontent.com/17361753/65781555-ce1dc400-e119-11e9-8d8f-5a1515347e66.png)

**Comment by britneywright** [comment]
@pauljamescleary Are you sure this is an issue? Paging would only show if there are more pending requests than the maxItems. The default is 100. I tested this locally by changing the maxItems to 1 and creating more than one pending batch change. I filtered by only open requests and was able to page through the results.

**Comment by remerle** [comment]
Seems easy to verify and fix if it's reproducible.
