### ISSUE TITLE
Add Logging around sent notifications in the API

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#852]
**Motivation**
There are no log statements when we emit notifications from the API. 

**Scope of change**

- `AllNotifiers` - wrap the individual `notify` `IO` with a `monitor` function

```scala
final case class AllNotifiers(...) extends Monitored {
...
  def notify(notifier: Notifier, notification: Notification[_]): IO[Unit] =
    monitor(notifier.getClass.getSimpleName) {
      notifier.notify(notification).handleErrorWith { e =>
        IO { logger.error(s"Notifier ${notifier.getClass.getSimpleName} failed.", e) }
      }
  }
...
```

**Comment by ericcheatham** [comment]
Hi! This looks like you have a fairly solid understanding of what you need done here. Mind if I take this one?

**Comment by britneywright** [comment]
Go for it @ericcheatham, let us know if you have any questions!
