### ISSUE TITLE
Global recordset search

### ISSUE THREAD

**Issue by britneywright** [vinyldns/vinyldns#861]
## Current state of recordset search and access in VinylDNS

Recordsets are only accessible through zones. The requesting user must have access to the zone as a member of the zone owner group, with a read, write or delete ACL rule, or as system admin. 

With shared zones in particular users own recordsets but do not have the ability to view their current state if they don't have access to the zones the recordsets is in. Additionally, we've seen that groups own individual recordsets across many zones, so there's a need to list recordsets beyond the zone scope. Lastly we want to give users autonomy to look up recordsets and find owner groups if DNS conflicts arise.   

## API Endpoints

Proposing three routes, two would be new, one already exists but will have additional query parameters.

- List all recordsets in VinylDNS
```
GET /recordsets
```

- List all records for a given zone (this endpoint already exists)
```
GET /zones/:zoneId/recordsets
```

- List all records owned by a given group. Direct record ownership only. Not including indirect ownership through zone ownership or ACL rules.
```
GET /groups/:groupId/recordsets
```

## Parameters
 | Name | Type | Description |
 |------------|------|------|
 | recordNameFilter  | string  | Text to filter against the recordset name attribute. case-insensitive. exact match unless wildcards (`*`) are used. |
  fqdnFilter  | string  | Text to filter against FQDN attribute. case-insensitive. exact match unless wildcards (`*`) are used. |
 | recordTypes  | string  | A list of comma separated record types. Default is all record types if not provided. |
 | direction  |  string | The direction of the sort. Either `asc` or `desc`. Default: `desc` |
 | sort  |  string | What to sort results by. `fqdn`, `created`, `updated`. Default: `fqdn`  |
 | since  | date-time | Only recordsets updated at or after this time. This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ. | 
 | startFrom  | string | Recordset ID. Should be set to the nextId that is returned on the previous response to return the next page of results. | 
 | maxItems  | integer | The number of items to return in the page. Valid values are 1 to 100. Defaults to 100 if not provided. | 

## Response Attributes
| Name | Type | Description |
|------------|------|------|
| recordsets  | array  | Array of recordsets. See recordset response for attributes. |
| startFrom  | string  | startFrom sent in request. Will not be returned if not provided |
| maxItems  | string  | maxItems sent in request. Default is 100. |
| sort  |  string | Given sort string `fqdn`, `name`, `created`, `updated`. Default to `fqdn` if not provided.  |
| nextId  | string  | startFrom sent in request. Will not be returned if not provided |
| direction  |  string | The given direction of the sort `asc` `desc`. Default to `asc` if not provided. |
| recordNameFilter  | string  | Requested record name to filter against. will not be returned if not provided. **Note:** only for zone recordset endpoint. |
| fqdnNameFilter  | string  | Requested fqdn to filter against. will not be returned if not provided. **Note**: only for groups and global recordset endpoints. |
| recordTypes  | string  | A list of comma separated record types requested. Will not be returned if not provided. |
| since  | string | Given date time to look for updated recordsets. Will not be returned if not provided. | 
| ipAddressFilter | string | Filter PTR records by their IP address formatted name |

  
### Recordset Response Attributes
| Name | Type | Description|
|------------|------|------|
| fqdn  | string  | Full qualified domain name |
| type  | string  | DNS record type |
| zoneId  |  string | The ID of the zone the record is in |
| name  | string  | Record name, Does not include the zone name |
| zoneName  |  string | The name of the zone the record is in |
| ttl  |  long | the TTL in seconds for the recordset  |
| status  | string | The current state of the Recordset. `Active`, `Inactive`, `Pending`, `PendingUpdate`, `PendingDelete` | 
| created  | date-time | The timestamp (UTC) when the recordset was created. ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ. | 
| updated  | date-time | The timestamp (UTC) when the recordset was most recently updated. ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ. | 
| records  | array of RecordData | Array of record data, a single RecordSet can have multiple DNS records as long as they are all the same type and the type supports multiple records | 
| accessLevel  | string | Access the requesting user has to the recordset. `None`, `Read`, `Delete` | 
| ownerGroupId  | string | The ID of the group that owns the record | 
| ownerGroupName  | string | The name of the group that owns the record | 
    
## Access
All authenticated, unlocked users should be able to make requests to these endpoints.
This is a change for the existing recordsets by zone endpoint. It is currently restricted based on zone access.

### Records
```
/records
```

New page in the portal at the root level.

<img width="1087" alt="Screen Shot 2019-10-03 at 1 43 54 PM" src="https://user-images.githubusercontent.com/4439228/66150878-22c2b280-e5e4-11e9-8571-2145e75722a6.png">
Table headings:

| FQDN | Type |	TTL |	Record Data | Zone Type | Owner Group Name | Actions |
|------|------|-----|-------------|---------|---------|---------|

Table options:
- Sort by FQDN in ascending or descending order. Default to ascending.

Search options:
- FQDN, wildcard support
- Owner group name. See about making this predictive/autocomplete, otherwise drop down of group names.
- Filter by record type. Default to all.

### Group Records
```
/groups/:groupId/records
```
Similar to current Zone area of the site, make tabbed pages in the Group. One for the existing group data, "Membership" and another for the new data, "Records". Explicit routing is not required, but would be an improvement over our existing tab behavior.

<img width="1097" alt="Screen Shot 2019-10-03 at 12 14 58 AM" src="https://user-images.githubusercontent.com/4439228/66098998-e5720c80-e572-11e9-9b3a-611bedaf4599.png">

Table headings:

| FQDN | Type |	TTL |	Record Data |	Actions |
|------|------|-----|-------------|---------|

Table options:
- Sort by FQDN in ascending or descending order. Default to ascending.

Search options:
- FQDN, wildcard support.
- Filter by record type. Checkboxes. Defaulted to all.

### Zone Records
```
/zones/:zoneId
```

Existing page with proposed modifications.

Table updates:
- Sort by Name in ascending or descending order. Default to ascending.

Search updates:
- Filter by record type. Checkboxes. Defaulted to all.

  
Table headings:

| FQDN | Type |	TTL |	Record Data |		Owner Group Name  |Actions |
|------|------|-----|-------------|---------|---------|

Table options:
- Sort by FQDN in ascending or descending order. Default to descending.

Search options:
- FQDN, wildcard support.
- Filter by record type. Checkboxes. Defaulted to all.

## Considerations
API & Portal:
- Linking to groups in the portal will require access validation changes in the API.

API:
- Should the default direction change from `asc` to `desc` if the sort is `created` or `updated`
- Need to think about IP address search, ho we'd do it and how to address clashes with other filters a user might pass in.

Portal:
- If we allow updating records in the Groups and Records areas we should only allow TTL, Record Data and Owner Group changes. Should not allow changing the FQDN which could change the record name and/or the zone.

**Comment by pauljamescleary** [comment]
@britneywright nice!  I do think we should just standardize on `recordNameFilter` across all endpoints.  There are installations that have dotted hosts everywhere, so those can be _really_ close to an FQDN.

Also, the interplay between the various params can become problematic if we have **both** an `ipAddressFilter` and a `recordNameFilter`

**Comment by mitruly** [comment]
Good discussion points/proposal @britneywright - a few concerns outlined below.

## API Endpoints
> List all records owned by a given group. Direct record ownership only. Not including indirect ownership through zone ownership or ACL rules.
> GET /groups/:groupId/recordsets

Regarding recordsets by group, `GET /recordsets/groups/:groupId` is more aligned with our existing API syntax

## Parameters
Having `updated` as a parameter makes more sense than introducing a new term (`since` for `updated`).

For filters, do we really need to have both a record name and FQDN if we support fuzzy matching? FQDN filtering should suffice.

In implementation, the `fqdn` index itself is not unique; this index would have to be `fqdn` + `recordType` to achieve uniqueness. Note that we _don't yet_ have this index on our record set table and need to add this. We should also either fully detail the sorting index (e.g. `(fqdn, recordType)`) or maybe allow users to choose sub-sorting fields. In other words, what are the indices/sub-sort proposed for `created`/`updated` sorts?

## Response Attributes
`name` sort isn't mentioned in parameters section. Also don't see the need for a record set name filter/sort since it would largely follow `fqdn`. Same comments as above regarding `recordNameFilter` and `since` fields.

Due to the nature of how record set data is stored, an IP filter may complicate things. Is this needed for the initial iteration?

## Records
Should this endpoint be `/recordsets` for consistency with the API?

## Group Records
Feel that this should be `/recordsets/groups/:groupId`

Having an interface for managing records introduces a lot more issues with interplay.

We would also need to use some context of `zoneId` to also identify records that exist in private zones that the group owns, since there would most likely be records without owner group assigned here. This would complicate the intention to just utilize `fqdn`, so this should be removed from the initial design at the very least.

**Comment by britneywright** [comment]
I chose to structure the endpoint as `/groups/:groupId/recordsets` because that follows the same structure as our current recordsets by zone endpoint `zones/:zoneId/recordsets` As well as the way we get group members and admins. `/groups/:groupId/members` and `/groups/:groupId/admins`. The routes end with the objects we want to return.

**Comment by pauljamescleary** [comment]
@britneywright @mitruly I am ok with the way it is here.  In following rest, how do you represent the list of recordsets owned by a group?  A path `/groups/:groupId/recordsets` is rather idiomatic from that standpoint.

I still think we could explore OpenAPI eventually (or maybe GraphQL) and these would just come out of the box.

**Comment by britneywright** [comment]
Some feedback I got about PTR search:
- Users would want to see the PTR record that corresponds to an A or AAAA record when searching
- Users would want to look up PTR records by IP and also abbreviated forms of the IPv6 records

e.g. of possible IPv6 lookup
```
2620:0000:0e50:0002:0000:0000:0000:0001
2620:0:e50:2:0:0:0:1
2620:0:e50:2::1
```

**Comment by mitruly** [comment]
@britneywright To confirm (as we already support `recordNameFilter`, `startFrom` and `maxItems` at the endpoint), we're proposing to:
- Allow `recordNameFilter` to also capture matches in record data
- Support `recordTypes` (or `recordTypeFilter`, to be consistent with `recordNameFilter`)

`recordTypeFilter` should be easy enough as `type` is an exposed column in our database. `recordNameFilter` will require a bit of thought as:
- We serialize our data as a blob and we would have to deserialize them
- We need to think about what record data makes sense to also apply a record data sort to. This is straight-forward for `PTR`, `A` and `CNAME`, but do we care about NS, CNAME, etc? Does it make sense to simply add a "sort name" relationship table (similar to our `membership` table) where when a record is created/updated, the corresponding entries in the relationship table are updated as well?
- Regardless of the implementation, this will most likely require a data migration of _some_ level

It seems reasonable enough from the initial spike to support `sort` in some capacity, though we'd have to figure out how flexible we want to allow this to be (e.g. allow users to configure primary and sub-sort values, etc.)

**Comment by britneywright** [comment]
I took out sort for the moment because of the potentioal complexity. Previously the request was for sort on any column and perhaps secondary sort. If we allow filter on name (and possibly data) and record type, it could mitigate the need for sort. Maybe we could start with just sort on record name.

**Comment by mitruly** [comment]
@britneywright that's a good point - `recordName` sort may actually suffice if we're supporting  other filters. As you mentioned, sorting can be expanded in the future.

**Comment by pauljamescleary** [comment]
> Some feedback I got about PTR search:
> 
> * Users would want to see the PTR record that corresponds to an A or AAAA record when searching
> * Users would want to look up PTR records by IP and also abbreviated forms of the IPv6 records
> 
> e.g. of possible IPv6 lookup
> 
> ```
> 2620:0000:0e50:0002:0000:0000:0000:0001
> 2620:0:e50:2:0:0:0:1
> 2620:0:e50:2::1
> ```

@britneywright for "Users would want to see the PTR record that corresponds to an A or AAAA record when searching", do you mean they would search for an FQDN and get back A, AAAA, and PTR in the same search?  Wondering if you could give an example.

"Users would want to look up PTR records by IP and also abbreviated forms of the IPv6 records" this is reasonable and expected.  We have the ip4s library that should make it easy to parse from any string into an IPv6 record, likely similar with IPv4.  This makes a TON of sense.   However, does it make sense to search in a CIDR range?  In theory we could do that as well.

**Comment by britneywright** [comment]
If there's an A record with a corresponding PTR in VinylDNS, when someone searches for the A record, `f1.example.com.` for example, the desired results would look something like:

| FQDN | Type |	TTL |	Record Data | Zone Type | Owner Group Name | Actions |
|------|------|-----|-------------|---------|---------|---------|
| f1.example.com. | A |	7200 |	1.1.1.1 | Shared | Unowned | |
| 1.1.1.1.in-addr.arpa. | PTR |	7200 |	f1.example.com.  | Shared | Unowned | |

Both the A and PTR records are returned. If we're able to search against the record name and record data this could happen naturally (they might not be grouped together, but we can hold that thought). If we don't search against record name and record data we would need to determine some other way of finding the corresponding records.

**Comment by britneywright** [comment]
Some additional feedback:
- We should probably require a string to search on for the recordset search endpoint that spans all zones and groups. I was thinking a minimum length to characters, or make that configurable.
- Default to no records showing in the portal on the Records page, only show records after a user searches

**Comment by jhg03a** [comment]
As an operator, I want a way to search IPs or names across all VinylDNS zones.  As I'm cleaning up existing brownfield records as part of decommissioning servers, I need to locate all records associated with an individual host.  This includes but is not limited to A, AAAA, CNAME, NS, PTR, TXT.  This also extends into values of said records.  For example locating when decomissioning an authoritative DNS server, finding upstream NS records which reference it among others so that the upstream NS record may also be cleaned up.  A second sub use case is finding reverse DNS PTR records to clean those up as well.
