### ISSUE TITLE
Quiet illegal header warnings from akka-http

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#864]
**Motivation**
We are seeing regular log entries like `(a.a.ActorSystemImpl:86) | Illegal header: Illegal 'authorization' header: Invalid input '/'` that are not consequential to the health of the application.  Let's see if we can quiet this somehow.

**Scope of change**
Configure akka-http and/or logback to quiet that log entry

**Comment by pauljamescleary** [comment]
According to documentation here - https://doc.akka.io/docs/akka-http/current/configuration.html

We should be able to simply set this flag in our reference.confs...

```
illegal-header-warnings = off

Possibly...
ignore-illegal-header-for = [] // not sure what it would be, Authorization, authorization, unsure
```

## Scope of work

1. Spin up akka-http locally by starting `sbt` and running `reStart`
2. Run a `curl` and re-create the warning message (document in PR), you would have to put a `/` character in the `Authorization` header in the `CURL` to re-create.
3. Modify the `api/src/main/resources/reference.conf` `akka.http` config section to ignore illegal header warnings
4. Re-run `curl` from Step 2 and verify the warning is gone.

**Comment by picimaci** [comment]
I'd like to take this issue.

**Comment by britneywright** [comment]
Assigned it to you @picimaci. Let us know if you have any questions.

**Comment by picimaci** [comment]
Thanks! I didn't have time last week but I'll hopefully get to it today or tomorrow.

**Comment by remerle** [comment]
Should be a quick fix. We're ultimately moving away from akka-http, but this seems like low-hanging fruit in the meantime.
