### ISSUE TITLE
Portal displays "Internal 500 error" (mysql) when doing group membership operations

### ISSUE THREAD

**Issue by xmtrcv** [vinyldns/vinyldns#868]
**Describe the bug**
When adding or deleting users, or toggling Group Manager for users, the portal displays an "HTTP 500 (Internal Server Error): There was an internal server error." banner.

**VinylDNS Version**
0.9.4-SNAPSHOT

**To Reproduce**
1. Click on Groups
1. Click View for an existing group (ex. `testGroup`)
2. Enter username (uid) in 'NT User Name' field and click 'Add Group Member'
3. User is added to group; HTTP 500 error banner is displayed at top of portal page
4. Click `Group Manager` toggle; HTTP 500 error banner is displayed at top of portal page
5. Click 'Delete' button for user; HTTP 500 error banner is displayed at top of portal page

Latent Effects:
1. Even when deleted from group, group shows in user's group list, with no interaction buttons ('View' 'Edit' 'Delete')
2. Once a user is added and deleted from an admin group for a zone, user has full read,write,edit access for zone, even if ACL restricting user is added later.

**Expected behavior**
Expected behavior is "user" is added to and removed from groups with no issues; with group membership displays and ACLs being respected.

**Screenshots**
none

**Stack trace or error log output**
`docker logs vinyldns-api`:
```
2019-10-08 15:50:33,336 [test] ERROR | (a.a.ActorSystemImpl:73) | Error during processing of request: '(conn=23814) You have an error in your SQL syntax; check the manual that corresponds to your MySQ
L server version for the right syntax to use near ')' at line 1'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler. 
java.sql.SQLSyntaxErrorException: (conn=23814) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
--- 8< --- snip ---
Caused by: java.sql.SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
Query is: INSERT IGNORE INTO membership (user_id, group_id) VALUES 
java thread: VinylDNS-akka.actor.default-dispatcher-335
        at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:163) ~[org.mariadb.jdbc.mariadb-java-client-2.3.0.jar:na]
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:280) ~[org.mariadb.jdbc.mariadb-java-client-2.3.0.jar:na]
        at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:223) ~[org.mariadb.jdbc.mariadb-java-client-2.3.0.jar:na]
        ... 79 common frames omitted
```

**Additional context**
Current test configuration is:
```
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS                                NAMES
51007ee207b3        vinyldns/api:0.9.4-SNAPSHOT      "/opt/docker/bin/api"    25 minutes ago      Up 25 minutes       0.0.0.0:9000->9000/tcp               vinyldns-api
0fdc91ec1abb        mysql:5.7                        "docker-entrypoint..."   4 days ago          Up 4 days           33060/tcp, 0.0.0.0:19002->3306/tcp   vinyldns-mysql
1da684bf8d12        vinyldns/portal:0.9.4-SNAPSHOT   "/opt/docker/bin/p..."   4 days ago          Up About an hour    0.0.0.0:9001->9001/tcp               vinyldns-portal
```

api/docker.conf:
```
vinyldns {

  data-stores = ["mysql"]

  mysql {
    settings {
      name = "vinyldns"
      driver = "org.mariadb.jdbc.Driver"
      migration-url = "jdbc:mariadb://vinyldns-mysql:3306/?user=root&password=pass"
      url = "jdbc:mariadb://vinyldns-mysql:3306/vinyldns?user=root&password=pass"
      user = "root"
      password = "pass"

      connection-timeout-millis=5000

      max-lifetime = 900000
      maximum-pool-size = 30
      register-mbeans = true

      idle-timeout = 10000
      minimum-idle = 20

      # these database settings are recommended here https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration
      # as well as here http://assets.en.oreilly.com/1/event/21/Connector_J%20Performance%20Gems%20Presentation.pdf
      # and here https://www.facebook.com/notes/mysql-at-facebook/jdbc-connection-overheads/10152027251270933/
      my-sql-properties = {
        cacheServerConfiguration=true
        prepStmtCacheSize=50
        prepStmtCacheSqlLimit=2048
        cachePrepStmts=true
        useServerPrepStmts=true
        useLocalSessionState=true
        useLocalTransactionState=true
        cacheResultSetMetadata=true
        rewriteBatchedStatements=true
      }

    }

    repositories {
      batch-change {
      }
      record-set {
      }
      user {
      }
      zone {
      }
      record-change {
      }
      zone-change {
      }
      group {
      }
      group-change {
      }
      membership {
      }
    }
  }

  queue {
    class-name = "vinyldns.mysql.queue.MySqlMessageQueueProvider"

    polling-interval = 250.millis
    messages-per-poll = 10

    settings = {
      name = "vinyldns"
      driver = "org.mariadb.jdbc.Driver"
      migration-url = "jdbc:mariadb://vinyldns-mysql:3306/?user=root&password=pass"
      url = "jdbc:mariadb://vinyldns-mysql:3306/vinyldns?user=root&password=pass"
      user = "root"
      password = "pass"

      # see https://github.com/brettwooldridge/HikariCP
      connection-timeout-millis = 1000
      idle-timeout = 10000
      max-lifetime = 30000
      maximum-pool-size = 5
      minimum-idle = 1

      my-sql-properties = {
        cachePrepStmts=true
        prepStmtCacheSize=250
        prepStmtCacheSqlLimit=2048
        rewriteBatchedStatements=true
      }
    }
  }

...

```

**Comment by pauljamescleary** [comment]
@xmtrcv you have set the standard for bug reports, thank you :)

**Comment by pauljamescleary** [comment]
@xmtrcv I am able to recreate, somehow membership was attempted to be added and the memberids to be added to the group was empty?

Output from my recreation...

```
[info]   Cause: java.sql.SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
[info] Query is: INSERT IGNORE INTO membership (user_id, group_id) VALUES 
```

I will backtrack into how this could possibly happen.

**Comment by pauljamescleary** [comment]
@xmtrcv tracking this down a little.  Here are some details to provide clues into what may have happened:

When adding a user to a group, the following e2e flow happens starting from the portal:

1. (portal) - get the user data for the username entered in the "Add User" field for the Group
1. (portal) - calls the backend `getUserDataByUserName` which performs the following:
    1. lookup the user info from LDAP
    1. lookup the user from the VinylDNS database
    1. if the user does not exist, create a user entry in the VinylDNS database
    1. return the user to the portal frontend
1. (portal) - adds the user to the group and issues an update group command to the API
1. (api) - calculates the delta, for new users calls `membershipRepo.addMembers`, here somehow the `addedMembers` is an empty set, and causes the issue you see.

Seems like we have a few issues to possibly correct:

1. Fix the api, make sure we do not call `addMembers` if there are no new members to be added.  We could also update the `MySqlMembershipRepository` to do nothing in the event `addMembers` passes in an empty set, which is probably the better approach.  Do the same with `removeMembers` as I think we may have a similar issue there but I don't think it would throw an exception.

2. Figure out what happened in the portal.  It appears as though `getUserDataByUsername` returned nothing (as opposed to failing), and that resulted in an `updateGroup` being called without actually being updated.  I am still tracking that part down, but we should blow up there if the user is not found.

**Comment by pauljamescleary** [comment]
@xmtrcv maybe others can check my math on the portal piece, but I am unable to find why this could happen from a portal perspective...

```scala
        for {
          userDetails <- IO.fromEither(authenticator.lookup(username))
          existingAccount <- userAccountAccessor.get(userDetails.username)
          userAccount <- existingAccount match {
            case Some(user) => IO(VinylDNS.UserInfo.fromUser(user))
            case None =>
              createNewUser(userDetails).map(VinylDNS.UserInfo.fromUser)
          }
        } yield userAccount
```

1. If the user is not found in LDAP, you would get a `UserDoesNotExistException` that would ultimately return as an error in the UI
2. If the user _IS_ found, then we attempt to find the user in the VinylDNS database.  That will result in a `Some` with the existing VinylDNS user OR `None`.  If any error occurs, then again it will bubble out as an error in the UI
3.  If the user exists in VinylDNS `Some` then we return the user we have in VinylDNS
4. If the user does not exist in VinylDNS `None` then we `createNewUser` and return that result.  If any errors occur they bubble out to the UI same as the rest of them

In the UI side, you can see...

```javascript
        return profileService.getUserDataByUsername($scope.newMemberData.login)
            .then(lookupAccountSuccess)
            .catch(function (error) {
                handleError(error, 'profileService::getUserDataByUsername-failure-catch');
            });
```

That `handleError` should popup an error.

Maybe @mitruly or @britneywright can also check my math.

**Comment by xmtrcv** [comment]
I would like to add that the test integration that generated this issue uses only `mysql` in `data-stores`.  An integration test using `mysql` & `dynamodb` in `data-stores` (i.e., the defauly config) does not have the same issue.  (Both test integrations are configured to use `mysql` for message queuing.
