### ISSUE TITLE
rename 'batch-change' AngularJS module to 'dns-change'

### ISSUE THREAD

**Issue by britneywright** [vinyldns/vinyldns#873]
**Motivation**
We renamed batch change in the portal UI to DNS Change. Then we changed the file names from batch-change to dns-change. We should change the batch-change AngularJS module that's now in `/modules/portal/public/lib/dns-change` to "dns-change" as well as the underlying controllers, service and directive.

**Scope of change**
- rename the module, directive, controllers and service in `/modules/portal/public/lib/dns-change`
- update the controller names at the bottom of the files:
  - `dnsChangeDetail.scala.html`
  - `dnsChangeNew.scala.html`
  - `dnsChanges.scala.html`

**Comment by JoshKessler** [comment]
I'd like to work on this
