### ISSUE TITLE
Improve help text on DNS Change form

### ISSUE THREAD

**Issue by britneywright** [vinyldns/vinyldns#879]
Per user feedback, we should try to improve the help text on the DNS Change form so users better understand what information goes in what fields.

One suggestion is to have the heading "Input Name" include the help text "existing name" and the heading "Record Data" have the help text "alias"

**Comment by remerle** [comment]
This should be overhauled as part of #968

**Comment by nspadaccino** [comment]
Addressed in https://github.com/vinyldns/vinyldns/issues/968
