### ISSUE TITLE
Allow flyway to always run migrations

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#89]
**Motivation**
Currently, we run flyway out of band via a "migration runner".  This makes things extremely difficult for other VinylDNS users, as they would have to

1. Build the assembly / fat jar
2. Run the `MigrationRunner`

Flyway has support for "locking" to ensure that only _one_ process is running migrations.

**Scope of change**
1. Remove the db migration runner
2. When `VinylDNSJDBC` starts up, _always_ run flyway migrations

**Comment by rebstar6** [comment]
crossing this with https://github.com/vinyldns/rfcs/pull/3, if someone has no jdbc repos, do we not even flyway? i think yes, just confirming

**Comment by rebstar6** [comment]
also, we used to use flyway for other kinds of migrations (like, adding things to dynamo)...i assume moving forward we will not be doing that (?).

**Comment by pauljamescleary** [comment]
@rebstar6 I think moving forward the plan is to have a `Datastore.initialize` function and leave it up to the database implementation.   That is in the RFC.

This is just a small first step to correct this issue until we get the RFC implemented and everything shuffled around.  The way we do migrations really is stupid.  Just always run the migrations is a small code fix (and potentially nerve racking deployment).

The main issue is we have no schema changes.  We could add a small, inconsequential migration as part of this just to ensure deployment has no issues.
