### ISSUE TITLE
Record set search by zone enhancements

### ISSUE THREAD

**Issue by britneywright** [vinyldns/vinyldns#896]
From #861 discussion.

## Existing API Endpoint:

```
GET /zones/:zoneId/recordsets
```

## Current Request Parameters

 | Name | Type | Required | Description |
 |------------|------|---|------|
 | recordNameFilter  | string  | No | Characters that are part of the record name to search for.  |
  startFrom  | any  | No | In order to advance through pages of results, the startFrom is set to the nextId that is returned on the previous response. |
 | maxItems  | integer  | No | The number of items to return in the page. Valid values are 1 to 100. Default is 100. |

## Proposed Request Parameters

 | Name | Type |  Required | Description |
 |------------|------|---|------|
 | recordTypeFilter | string | No | A list of comma separated record types. Won't filter results by record type if none are provided. |
| sort | string | No | Direction of sort by record name. Either `asc` or `desc`. Default is `asc`|

## API Changes
RecordSetRouting:
- update the `getRecordSets` Endpoint to include recordTypes, and sort as optional parameters.
- set the sort default value to "asc"
- validate that given sort is either "desc" or "asc" (case-insensitive) and convert to SortDirection enumerable (need to create)
- validate that given recordTypes are valid and convert to an optional list of RecordTypes
- rename `getRecordSets` to `getRecordSetsByZone`
- update `ListRecordSetsResponse`

RecordSetService:
- Update `listRecordSets` to include new parameters

RecordSetServiceAlgebra:
- Update `listRecordSets` to include new parameters

RecordSetRepository:
- Update `listRecordSets` to include new parameters

MySqlRecordSetRepository:
- Update `listRecordSets` to include new parameters

DynamoDBRecordSetRepository:
- Update `listRecordSets` to include new parameters

## Portal Changes
VinylDNS.scala:
- Rename `getRecordSets` to `getRecordSetsByZone` include new parameters
- Change parameter from `id` to `zId`

routes:
- Change `@controllers.VinylDNS.getRecordSets(id: String)` to  `@controllers.VinylDNS.getRecordSetsByZone(zid: String)`

service.records.js:
- Change `getRecordSets` to `getRecordSetsById`

controller.records.js:
- Update recordService calls from `getRecordSets` to `getRecordSetsById`
- Include new query parameters

manageRecords.scala.html:
- Add sort on Name column. Default to ascending.
- Add filter by record type. List of checkboxes. Default is All. Consider only showing record types that are valid in the given zone. For example don't show PTR records as an option in forward zones.

## Documentation Changes
API:
- Add new parameters to List / Search RecordSets

Portal:
- Update screenshots on Manage Records page

## Tooling Changes:
The tools can be updated at a later point as the current query parameters aren't changing in terms of requirements or type and the new query parameters are optional. These are initial recommendations, may not include all files and functions that require updates.

- go-vinyldns:
  update `RecordSetsListAll` in [recordsets.go](https://github.com/vinyldns/go-vinyldns/blob/master/vinyldns/recordsets.go)
 update `RecordSetCollector` in [recordsets.go](https://github.com/vinyldns/go-vinyldns/blob/master/vinyldns/recordsets.go)
update `RecordSetsResponse` in [recordsets.go](https://github.com/vinyldns/go-vinyldns/blob/master/vinyldns/recordsets_resources.go) 
may need to to create recordset specific ListFilter see [resources.go](https://github.com/vinyldns/go-vinyldns/blob/master/vinyldns/recordsets_resources.go) 
consider `RecordSetsListAll` naming as it will relate to future recordset search outside of zones

- vinyldns-cli:
  don't think changes are needed as it calls out to go-vinyldns
  consider `recordSets` naming as it will relate to future recordset search outside of zones

- vinyldns-js:
  add new query parameters for `getRecordSets` in [vinyldns.js](https://github.com/vinyldns/vinyldns-js/blob/master/src/vinyldns.js#L104-L114)
 consider `getRecordSets` naming as it will relate to future recordset search outside of zones

- vinyldns-java:
   update [ListRecordSetsRequest](https://github.com/vinyldns/vinyldns-java/blob/master/src/main/java/io/vinyldns/java/model/record/set/ListRecordSetsRequest.java)
  update [ListRecordSetsResponse](https://github.com/vinyldns/vinyldns-java/blob/master/src/main/java/io/vinyldns/java/model/record/set/ListRecordSetChangesResponse.java)
  consider `ListRecordSetsRequest` and `ListRecordSetsResponse` naming as it will relate to future recordset search outside of zones

- terraform-provider-vinyldns:
  don't think changes are needed
 
- vinyldns-ruby:
  update RecordSet search in [zone.rb](https://github.com/vinyldns/vinyldns-ruby/blob/master/lib/vinyldns/api/zone/zone.rb#L107-L112)

- vinyldns-python:
  update `ListRecordSetsResponse` in [record.py](https://github.com/vinyldns/vinyldns-python/blob/master/src/vinyldns/record.py#L211-L227)
  update `list_record_sets` in [client.py](https://github.com/vinyldns/vinyldns-python/blob/master/src/vinyldns/client.py#L545-L566)
  consider `list_record_sets` naming as it will relate to future recordset search outside of zones

**Comment by mitruly** [comment]
Great write up, @britneywright.

## API

> A list of comma separated record types. Default is all record types if not provided.

Regarding the API `recordTypes` parameter where the default is all, I think it would make sense to change this to `recordTypeFilter` (with default being none) since it lends itself better to our database querying.

This can still play with the checkboxes approach in the portal where if not all of the checkboxes are selected, we can send in specific record types as the filter; otherwise, don't send any parameter if all the types are selected.

## Portal

> Consider only showing record types that are valid in the given zone. For example don't show PTR records as an option in forward zones.

Regarding the record types that are valid in the given zone, this would be better delegated as an additional enhancement since the record set modals themselves don't currently have restrictions on creating records.

> Add sort on Name column. Default to ascending.

Just wanted clarification on whether the sort on name would be something like a clickable toggle, where we would change the UI like flipping an up/down arrow to perform the sort.

## Tooling
`vinyldns-js` shouldn't need updates since `getRecordSets` already supports `queryOpts` (i.e. query options).

**Comment by britneywright** [comment]
@mitruly correct on the portal sort. Some type of directional arrow on the Name heading.

For vinyldns-js I thought the parameters listed above the function were some time of typing, but that's just documentation? Should still update those when the new parameters are in place.
