### ISSUE TITLE
RFC: CNAME Auditing - Security feature

### ISSUE THREAD

**Issue by kontrolldkaos** [vinyldns/vinyldns#9]
Issue: DNS records can become stale, people forget to remove them. This can be an issue if it's a CNAME and the end point of the CNAME is no longer in control of the zone owner. This could lead to hijacking of that endpoint, which in turn could be a major security issue. 

RFC: Audit CNAMEs in a zone, this should be ran adhoc or on an interval by the zone owners and VinylDNS admins. Ideally an alert would show that the CNAME endpoint is no longer reachable and should be investigated. This should also be checked when initially importing a zone into Vinyl.

**Comment by pauljamescleary** [comment]
@kontrolldkaos - look for a complete RFC guide coming soon.  Thank you for capturing the start here.

The process will be to open a PR to create a new RFC document in the `rfcs` folder.  

The collaboration will take place in comments on that PR.  Amendments to the PR can be made as subsequent commits along the way.

Look forward to the discussion!

**Comment by kontrolldkaos** [comment]
@pauljamescleary I think that's the major indication of a potential issue. There may be other things that could be tied the endpoint's expected data, but initially it should be resolvable.

**Comment by pauljamescleary** [comment]
Ok, there are likely a few ways to spin this feature.  Let's get a PR open with an RFC attached.  I still have to create an RFC Readme, but essentially:

1. Create a new file in the rfcs folder called `0000-your-feature-name.md`.  Use the template.  It doesn't have to be fully populated initially
1. Open a PR and link it to this issue.
1. We will discuss / amend / make commits on the PR

It will be open for comments for a period.  Gotta discuss how long the comments period is.

Thanks @kontrolldkaos !

**Comment by pauljamescleary** [comment]
Closing this as it has moved over to the rfc repo for official review 🎉
