### ISSUE TITLE
Wildcard records cause others to fail

### ISSUE THREAD

**Issue by rebstar6** [vinyldns/vinyldns#91]
In our validations, for an add, we skip the initial existence check if there is a wildcard that matches the record, as it will resolve to something in that case (ex. `A *.test.com` exists, trying to add `A new.test.com`). However, we do not skip for CNAME wildcards even though they cause other records to resolve (ex. `CNAME *.test.com` exists, trying to add `A new.test.com`)

**VinylDNS Version**
0.8.0

**To Reproduce**
1. add a CNAME wildcard (*.zone.name.com)
2. try to add A record (some-a.zone.name.com)

**Expected behavior**
The A record should be added

**Comment by pauljamescleary** [comment]
Is this blocking someone?  Should we fix immediately?  Unclear on the severity of the issue (may want to update the issue template)

**Comment by rebstar6** [comment]
not a blocker, the team that brought it up said they have updated their docs so that users will always create A records first before wildcards, and they dont have many other records to create.

so can keep lower on the priority list
