### ISSUE TITLE
Improve Monitoring

### ISSUE THREAD

**Issue by mitruly** [vinyldns/vinyldns#918]
## Description
We should add logs around pertinent events to generate more insightful analytics to drive the product. The following breakdown groups logs and designs by events.

## Events
1.  **Routing error responses (API)**
In the main routes `BatchChangeRouting`, `MembershipRouting`, `RecordSetRouting` and `ZoneRouting` we want to log the error responses that are raised back to the user. This involves creating a helper function that uses SLF4J logger for the class to capture the error message and username before returning the user response.

1. **Routing error responses (portal)**
For membership, record set and zone routes, the VinylDNS portal invokes the API directly and returns the response back to the user so no additional logging is needed. However, for the DNS Changes (i.e. batch change in the API), there are validations that are done in the portal prior to submission which mimics API validations and rejects bad requests before they hit the API. Logging should be added in `dns-change-new.controller.js` to capture these errors in the event that `$scope.batchChangeErrors` is set along with the submitter username.

1. **Capture batch changes flagged for manual review**
We want to know how many changes are going to manual review.  Record in our logs the user submitting the request, each reason for manual review (based on the soft error) with frequency, the record owner group and total number of changes in the request. The motivation for this is to drive information needed for internal FAQs and other communication with users. This will primariily be in `BatchChangeService`.

1. **Capture manual review process metrics**
We want to know how long it takes for batch changes to be manually reviewed along with the final disposition (in `BatchChangeService`). For approve or reject, capture the delta between the submit time and review time, the user who submitted the request, the end state (approved or rejected). For scheduled changes, we also want to determine the delta between review and scheduled times. This will provide insight to drive service-level agreement (SLA) timelines and determine whether they are being fulfilled.

1. **Capture dotted host information in zone syncs and record changes**
VinylDNS does advocates for sub-domains over dotted hosts, though allows management of existing dotted hosts that are synced in. We should add metrics around dotted hosts for visibility for DNS operations team that may want to address how frequently dotted hosts are being created/updated.

1. **Capture any backend failures in logs**
We want to know how many partial failures we are encountering, which we are currently capturing in the `BatchChangeHandler`, though we need to provide more specific data for the requests that are failing. Make sure we update existing logging to include the record data and the reason for failure.

1. **Portal browser information**
While user agent and other custom headers tied to DNS requests are captured in the API, we need to make sure that the portal also captures browser information as not all requests successfully hit the VinylDNS API (e.g. DNS Change validations fail for new submission in portal). Currently we have `user-agent=unknown` in our portal logs.

**Comment by britneywright** [comment]
>  4. Capture manual review process metrics
The information we want here seems to be information we can get from the database

**Comment by remerle** [comment]
We'll address this as part of #967
