### ISSUE TITLE
Add User Lookup API Endpoint

### ISSUE THREAD

**Issue by jhg03a** [vinyldns/vinyldns#930]
**Is your feature request related to a problem? Please describe.**
As a consumer of the API, I'm a member of a shared VinylDNS Zone.  I can obtain Zone, Recordset, and Change data from the shared zone.  If I'm a member of the group which owns the zone, I can query the groups and group members (User objects).  There doesn't exist a current endpoint to supply a UserID and get back details about that user unless they're a member of a group I'm presently in.

**Describe the solution you'd like**
Just like there is an API endpoint to pass in a groupID to retrieve an arbitrary group, I'd like a similar one to resolve existing data obtained via Change object on a RecordSet belonging to a Zone.  It may also be useful to provide lookup methods for any other supported primary key fields such as username or email to get the ID guid.

**Describe alternatives you've considered**
I can make my own user lookup table based on my current group memberships, but that doesn't work very well in shared zones or long lived recordsets where users are offboarded and removed from groups.

**Comment by jhg03a** [comment]
Upon further review, it appears that maybe group members contained within groups may only have the UserID specified and no other fields populated.  This makes even local group member based lookups meaningless.

**Comment by pauljamescleary** [comment]
@jhg03a what user data would be returned?  We have to be careful with what user details we surface.  Do you have a proposal for a sample endpoint and JSON response payload?

This is something we have wanted for a while and seems like some low hanging fruit

**Comment by jhg03a** [comment]
At this point I'll take anything that helps to associate users with their UUID; username and/or email.  I've moved on from the project where I found this and settled on the UUID for now, so no rush but it is still a valid request for the future.

**Comment by pauljamescleary** [comment]
`GET /users/<uuid>` would be the endpoint

Return username + userid in the JSON payload.  Go with a json payload so we can optionally add additional information there in the future.

Note: need to add support for individual clients as well at some point, go-lang, js, etc.

**Comment by abhide** [comment]
@remerle @pauljamescleary Would like to work on this issue; if its ok with you?

**Comment by pauljamescleary** [comment]
Sounds great!
