### ISSUE TITLE
Add Member domain class

### ISSUE THREAD

**Issue by mitruly** [vinyldns/vinyldns#941]
**Motivation**
Based on the existing models, `Member` should be a model based off of group membership that links a user to a group with associated administrative privileges.

**Scope of change**
Existing `MembershipRepository` interactions should be updated to reflect the updates, with `saveMembers(..)` being updated to save a member rather than the individual components.

**Comment by remerle** [comment]
I feel like we can address this when we move to Scala 3 and rework the domain model (#967).
