### ISSUE TITLE
Create script for managing super users

### ISSUE THREAD

**Issue by remerle** [vinyldns/vinyldns#955]
There is no administrative interface, or config-level control over the super user.  Super users are controlled with a flag in the binary blob in the backing store, which is opaque from a query and update point of view.

**Describe the solution you'd like**
As a short term solution, as part of #953, VinylDNS should provide a script that can manage the super user flag.  This should be a simple solution with minimal dependencies as to limit documentation overhead.  It should assume that the data is stored in a MySQL database using the [VinylDNS protobuf definition](modules/core/src/main/protobuf/VinylDNSProto.proto).  It should provide the ability to set a given user as a super user, as well as remove the super user flag from a given user.

The expectation is that this is a management task that would not occur often, but this is still as stopgap until a more formal approach to role-based security and/or group management is provided.

_Suggest this be placed in a top-level `/scripts` directory to prevent it from being confused with the scripts in the `/bin` directory, which are more deployment related._

**Describe alternatives you've considered**
See #953 for context

**Additional context**
See #953 for context

**Comment by JanuszU** [comment]
If there you provide a data structure description then I could write a script.
YES it is definitely needed.

**Comment by pauljamescleary** [comment]
I created a PR for this - https://github.com/vinyldns/vinyldns/pull/956

Recommend python, just need to compile the proto.  I put it all in a docker file for right now, but the script can run anywhere as long as the proto is compiled and available
