### ISSUE TITLE
fix the left and top menu bars from scrolling

### ISSUE THREAD

**Issue by JanuszU** [vinyldns/vinyldns#959]
**Is your feature request related to a problem? Please describe.**
When you scroll a view, ie. zone records, the menu bar disapears from the view. (tested in FFox)

**Describe the solution you'd like**
Make the menus fixed so it is visible all the time

**Comment by pauljamescleary** [comment]
Thanks!

**Comment by pauljamescleary** [comment]
Less of a bug, more of a "fix the nav bar and header as you scroll" kind of thing, which is reasonable.  Should be accomplishable with CSS
