### ISSUE TITLE
Add support for additional DNS providers (e.g. AWS)

### ISSUE THREAD

**Issue by kontrolldkaos** [vinyldns/vinyldns#961]
**Is your feature request related to a problem? Please describe.**
AWS endpoints (NS or cloud instances) can become stale and inactive, causing a possibility for hijacking. This also applies to other external endpoints that are not within control of the network or organization doing DNS updates. 

**Describe the solution you'd like**
Add a feature that would allow teams to be alerted on intervals, set by teams, about their AWS endpoints. There could be some logic that allows those teams to do "health checks" via Vinyl, but this is could informational at this point. 

**Describe alternatives you've considered**
Using external scripts to check AWS endpoints and external endpoints or "just remember" (Just remember doesn't work)

**Additional context**
This would be a useful feature to create reports on, especially for security teams.

**Comment by pauljamescleary** [comment]
@kontrolldkaos Would the ideal approach be to use VinylDNS to _manage_ AWS?

I would like to design a feature to formalize "backends" in VinylDNS, so we can not only integrate via standard DNS/DDNS, but also to other DNS software including Route53.

The motivation is that we need an adapter mechanism that knows how to talk to these other backends (like Route53).  In this case, I imagine that expiration information would be available via an AWS API that we could talk to.  Similar capability could be added for Google and Azure.

Let me know your thoughts.  I am advocating for formalizing "backends" in VinylDNS that can have different implementations per DNS backend (including Route 53) as a stepping stone to this feature.

**Comment by remerle** [comment]
I think being able to managing delegated zones through their provided APIs would be neat.  Having more formal support for AWS et al would definitely be useful (especially if it could be an entirely self-service process).  If, through the APIs, we could schedule periodic checks (i.e., do the credentials still provided access to the zone) then we can more intelligently (and automatically) alert on stale NS records.

We still have the issue that an NS record can point anywhere, and that may be to a place that we cannot verify the zone's validity.  I don't know how you would handle this other than generating a report.  I'd imagine you'd need some roles and permissions as to who receives these reports and for which zones.  I imagine security teams wanting an aggregate view across multiple zones, as well as individual zone owners getting reminders.

**Comment by kontrolldkaos** [comment]
> @kontrolldkaos Would the ideal approach be to use VinylDNS to _manage_ AWS?
> 
> I would like to design a feature to formalize "backends" in VinylDNS, so we can not only integrate via standard DNS/DDNS, but also to other DNS software including Route53.
> 
> The motivation is that we need an adapter mechanism that knows how to talk to these other backends (like Route53). In this case, I imagine that expiration information would be available via an AWS API that we could talk to. Similar capability could be added for Google and Azure.
> 
> Let me know your thoughts. I am advocating for formalizing "backends" in VinylDNS that can have different implementations per DNS backend (including Route 53) as a stepping stone to this feature.

@pauljamescleary I think that's a good approach. If it's streamlined, even better. Reason I say streamlined, is because I am aware that there are issues with split horizon DNS zones. I do agree, if it's possible to get that state, with an adapter or another mechanism, then it is definitely a stepping stone to having an all in one DNS management solution. 

@remerle Definitely some sort of reporting feature would be great. I think it would be up to the implementer and maintainer of an organizations Vinyl instance to determine who should receive those reports. Having the feature available would be a value add IMO.

**Comment by pauljamescleary** [comment]
Rewording the headline.  Having a "Provider" Interface to support integration with other backends like cloud providers has long been on the wish list of things todo.  It is a meaty feature for sure; however, there are a small number of providers and an even smaller number of operations that need to be supported.

Some key features include:
1. Loading zone data
2. issuing individual updates
3. Configuring the provider - need some kind of configuration format for connecting to the provider and saving secrets.  How will this extend or replace the "ZoneConnection" model we have in place today?

Considerations:
1. The provider API would live in Core
2. Each provider should be its own separate submodule

Other features?

Recommend a prototype implementation of an AWS provider for Route 53, then we can review and shape the API

**Comment by pauljamescleary** [comment]
Bump as we are working onthis.

**Comment by pauljamescleary** [comment]
Have shaken out the backend stuff a few times.  Now, I have all functional tests passing (still all DNS), so that implies that the whole system works.

Creating a Route53 module now.  I have a lot of that baked in the PR.  Will continue to work on that.

Once the Route53 provider is in and tested would like to review the high level design before wrapping up as it is a big change (there will be a lot of unit tests that need to be touched, and added functional tests)

**Comment by pauljamescleary** [comment]
Considering this closed, as AWS support was merged and some issues have been fixed.  Additional cloud providers can be added as needed.
