### ISSUE TITLE
make possible other key algorithms than HMAC-MD5, maybe HMAC-SHA256

### ISSUE THREAD

**Issue by JanuszU** [vinyldns/vinyldns#964]
only HMAC-MD5 is possible for now

possibility of using stronger keys would be a nice enhancement

@pauljamescleary suggested that maybe it is possible to change a key name to "algorithm:keyName"

**Comment by pauljamescleary** [comment]
Thanks @JanuszU , yes it should be possible to make a change for the key name to prepend the algorithm and do a simple parse on it.

**Comment by remerle** [comment]
For reference:
https://github.com/vinyldns/vinyldns/blob/5d2f2b87da98196263db9d658b61ab5f3e43468d/modules/api/src/main/scala/vinyldns/api/domain/zone/ZoneViewLoader.scala#L41-L45

The TSIG ctor at line 45 defaults to `HMAC_MD5`.  An overloaded ctor takes the algorithm as the first parameter.

**Comment by pauljamescleary** [comment]
@remerle agreed on the constructor, however we specify the keys in more than just the dns config, we also specify it in the zone connection on the zone itself (it is a zone level override).  We could add a field to the protobuf that defaults to the existing, and then just add it to the zone connection.  That would likely be just as easy or easier than some parsing.

The downside would be, the UI would need to be updated as well to add an optional algorithm, though I don't think that is too difficult.

**Comment by pauljamescleary** [comment]
Maybe this is ready?  The approach would be:

1. Add a new `algorithm` field to the `VinylDNS.proto` file, make it required with a default of HMAC-MD5.  This could be an enum.
2. Add the field to the `ZoneConnection`
3. Change where we actually establish a connection to the DNS server with the DNS resolver to pass in the algorithm
4. Update the management tab of the Zone to allow the user to specify the algoirthm as a new field, ensure it gets passed along.  If not provided, it should be the default HMAC-MD5
5. Add a new key that is a different algorithm in the functional tests that has access to any of the test zones in the bind config, add a functional test that verifies sending in the algorithm allows a simple test (create zone, add a record, delete a record)
