### ISSUE TITLE
Overhaul CI/CD Process

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#972]
Should we move to Github Actions?  Are there benefits in terms of:

1. Build times?
2. Simplicity of secret management?
3. Ease of publishing releases to sonatype and docker via Github Actions>

**Comment by jhg03a** [comment]
We just made the transition ourselves with Apache TrafficControl.  The biggest thing we gained from it was the ability of PR authors to make changes to GHA without having to manage a separate trust for trusted contributors.  This also allowed us to leverage some of our more complicated test suites that have docker-compose based sidecars.

**Comment by pauljamescleary** [comment]
We punted on manual releases, it is possible in Travis but if we are going to revisit doing releases via CI it makes sense to take a look at it.  There is a lot of precedent at this point

**Comment by pauljamescleary** [comment]
I am going to move this to `Ready` and pick it up.  We need fully automated public releases, so we should be on actions, manage secrets in GH, and publicly release here as well.

Will need separate issues to follow suit for the client libraries

**Comment by pauljamescleary** [comment]
I recently merged in a PR for Github Actions for:

1. PR build (verify + func test)
2. Merge to master (publish docs)

@nimaeskandary was looking into Docker.  fwiw, we already have a full blown docker build and release under the `build` directory that we can use.  We can release docker images and then for the time being notary sign them out of band after publishing (at least based on what I have ready).

I would like an initial release process that 1) creates a draft github release with master, auto assigns the next version number and 2) builds and publishes the releases to docker hub.  That would be a good first step until we get the notary thing figured out.

**Comment by pauljamescleary** [comment]
The only remaining thing on this issue now is to create a github workflow that:

1. Does a semantic version bump
2. Runs the docker release which is just a shell script `/build/docker-release.sh -c -l -p` - the arguments are "clean latest push".  Make sure to use the version bump
3. Once complete, do a github release and create and push a git tag.  I actually think you can just create and push the git tag with the version `v0.9.7` for example and have another workflow pick up that event and generate the github release

Bonus points to generate a changelog on the Github release, looking back at commits / issues / prs or what have you since the prior release.  Seems like there are a few ways to do that.
