### ISSUE TITLE
Rename "DNS Changes" to "DNS Requests"

### ISSUE THREAD

**Issue by pauljamescleary** [vinyldns/vinyldns#994]
This would be a change only in the PORTAL, changing the term "DNS Change" to "DNS Request" instead.

Leave the backend for the portal and api alone.

1. Change the terms in the portal
2. Update the screen shots in the documentation

**Comment by P3trur0** [comment]
I can take this.

**Comment by P3trur0** [comment]
In the portal screen I see the following:

![image](https://user-images.githubusercontent.com/11474157/95137319-12e62d00-0768-11eb-84d0-74a7fc1500b8.png)

Do I have to modify the:

-  Changes
-  Change type
-  Add a change

labels also?

**Comment by pauljamescleary** [comment]
Thanks @P3trur0 , you do not need to modify "changes", "change type" or "add a change" like you showed.  The nav bar, the title displayed, the button that says "New DNS Change" should be "New DNS Request, and the docs.

If you do a scan in the codebase, there are also a number of things in javascript and such that say "DNS Change", those should be "DNS Request".

**Comment by remerle** [comment]
@pauljamescleary @P3trur0 

I don't see a need for this. There is no ambiguity in the current naming, and a change would require downstream users to update their documentation.

Suggest we leave this as-is pending a rewrite of the portal.

**Comment by pauljamescleary** [comment]
@remerle the motivation for this issue is in describing a "batch" of changes as I went through the UI prepping for some demoes and having to mock explain the concepts in the UI.  Today, the instructions would follow:

1. Click on "DNS Changes" to see your DNS changes
2. Click "New DNS Change" to submit DNS changes, many changes can live on a single DNS change?
3. Click "Add Change" to add multiple DNS changes to a single DNS change?
4. One of the DNS changes may need to be manually reviewed on a DNS change?

That wording is ambiguous, there is no clear separation between a "DNS Change" as a set of changes, a single change within a larger DNS change, and it also collides more generally when discussing "DNS Changes" more broadly

The proposal of using "DNS Request" is to make that separation more clear.  Originally it was called "Batch Changes" and "Batch Change" and that was a better separation of concepts than what is there today.

The proposal would read:

1. Click on "DNS Requests" to see the DNS requests that you have made
2. Click "New DNS Request" to submit DNS Changes.  Many changes can live on a single DNS Request.
3. Click "Add Change" To add multiple DNS changes to a single DNS Request
4. One of the DNS Changes may need to be manually reviewed on a DNS request

**Comment by remerle** [comment]
@pauljamescleary 

I understand your position, and it's valid. I just want to avoid UI changes that result in a lot of documentation housekeeping at this point.

Can we make this configurable? That seems like it would satisfy everyone's needs 🙂
